// Stage 7 (commit) of DATA-PIPELINE.md §2 — writes the validated ChainData straight into
// src/data/<chain_id>.ts, replacing the hand-typed file. git history (see run.ts) is the
// "free, zero-effort price archive" DATA-PIPELINE.md §2 promises.

import { writeFile } from "node:fs/promises";
import path from "node:path";
import type { ChainData } from "../../src/types.js";
import type { PipelineSource } from "./types.js";

function serializeChainData(data: ChainData): string {
  // JSON.stringify output is valid TS object-literal syntax; re-indent to 2 spaces to match
  // the rest of the codebase.
  return JSON.stringify(data, null, 2);
}

export async function writeChainDataFile(source: PipelineSource, data: ChainData): Promise<string> {
  const filePath = path.resolve(import.meta.dirname, `../../src/data/${source.chain_id}.ts`);
  const header = `// AUTO-GENERATED by scripts/pipeline (ROADMAP.md Milestone 4) — do not hand-edit.
// To fix a specific item, add/update it in data/overrides/${source.chain_id}.json instead;
// re-running the pipeline preserves override entries (DATA-PIPELINE.md §2).
// Last pipeline run: ${data.chain.last_updated}. Source: ${data.chain.source_url} (${data.chain.source_type}).

import type { ChainData } from "../types.js";

export const ${source.export_var_name}: ChainData = ${serializeChainData(data)};
`;
  await writeFile(filePath, header, "utf-8");
  return filePath;
}
