// AUTO-GENERATED by scripts/pipeline (ROADMAP.md Milestone 4) — do not hand-edit.
// To fix a specific item, add/update it in data/overrides/jollibee.json instead;
// re-running the pipeline preserves override entries (DATA-PIPELINE.md §2).
// Last pipeline run: 2026-08-11. Source: https://jollibeemenuprice.net/ (third-party-aggregator).

import type { ChainData } from "../types.js";

export const jollibee: ChainData = {
  "chain": {
    "id": "jollibee",
    "name": "Jollibee",
    "source_url": "https://jollibeemenuprice.net/",
    "source_type": "third-party-aggregator",
    "last_updated": "2026-08-11",
    "notes": "Illustrative Milestone-0 dataset — see DATA-PIPELINE.md §1 for the real source plan."
  },
  "items": [
    {
      "id": "jb-1-piece-chickenjoy-w-coke-float",
      "chain_id": "jollibee",
      "name": "1-piece. Chickenjoy w/ Coke Float",
      "category": "combo",
      "price": 134,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-6-pieces-chickenjoy-solo",
      "chain_id": "jollibee",
      "name": "6 – pieces. Chickenjoy Solo",
      "category": "main",
      "price": 467,
      "serves": 1,
      "main_servings": 6,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-w-pepsi-float",
      "chain_id": "jollibee",
      "name": "1-piece. Chickenjoy w/ Pepsi Float",
      "category": "combo",
      "price": 134,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-8-piece-chickenjoy-bucket-w-jolly-spaghetti-family-pan",
      "chain_id": "jollibee",
      "name": "8 – piece. Chickenjoy Bucket w/ Jolly Spaghetti Family Pan",
      "category": "combo",
      "price": 573,
      "serves": 8,
      "main_servings": 8,
      "carb_servings": 1,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-6-piece-chickenjoy-bucket-w-jolly-spaghetti-family-pan",
      "chain_id": "jollibee",
      "name": "6 – piece. Chickenjoy Bucket w/ Jolly Spaghetti Family Pan",
      "category": "combo",
      "price": 697,
      "serves": 6,
      "main_servings": 6,
      "carb_servings": 1,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-6-piece-chickenjoy-w-palabok-family-pan",
      "chain_id": "jollibee",
      "name": "6 – piece. Chickenjoy w/ Palabok Family Pan",
      "category": "combo",
      "price": 927,
      "serves": 6,
      "main_servings": 6,
      "carb_servings": 1,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "palabok"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-8-piece-chickenjoy-w-palabok-family-pan",
      "chain_id": "jollibee",
      "name": "8 – piece. Chickenjoy w/ Palabok Family Pan",
      "category": "combo",
      "price": 1033,
      "serves": 8,
      "main_servings": 8,
      "carb_servings": 1,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "palabok"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-solo",
      "chain_id": "jollibee",
      "name": "1 – piece. Chickenjoy Solo",
      "category": "main",
      "price": 85,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-burger-steak-half-jolly-spaghetti-super-meal-w-drink",
      "chain_id": "jollibee",
      "name": "1 – piece. Chickenjoy, Burger Steak & Half Jolly Spaghetti Super Meal w/ drink",
      "category": "combo",
      "price": 218,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "burger steak",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-chickenjoy-bucket-family-meals",
      "chain_id": "jollibee",
      "name": "Chickenjoy Bucket Family Meals",
      "category": "combo",
      "price": 745,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-4-piece-chickenjoy-family-box-solo",
      "chain_id": "jollibee",
      "name": "4 – piece. Chickenjoy Family Box Solo",
      "category": "main",
      "price": 338,
      "serves": 4,
      "main_servings": 4,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-w-creamy-macaroni-soup-drink",
      "chain_id": "jollibee",
      "name": "1 – piece. Chickenjoy w/ Creamy Macaroni Soup & drink",
      "category": "combo",
      "price": 186,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-creamy-macaroni-soup-solo",
      "chain_id": "jollibee",
      "name": "1 – piece. Chickenjoy & Creamy Macaroni Soup Solo",
      "category": "combo",
      "price": 167,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-burger-steak-w-drink",
      "chain_id": "jollibee",
      "name": "1 – piece. Chickenjoy & Burger Steak w/ drink",
      "category": "combo",
      "price": 162,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "burger steak"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-burger-steak-solo",
      "chain_id": "jollibee",
      "name": "1 – piece. Chickenjoy & Burger Steak Solo",
      "category": "combo",
      "price": 135,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "burger steak"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-palabok-w-drink",
      "chain_id": "jollibee",
      "name": "1 – piece. Chickenjoy & Palabok w/ drink",
      "category": "combo",
      "price": 233,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "palabok"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-palabok-solo",
      "chain_id": "jollibee",
      "name": "1 – piece. Chickenjoy & Palabok Solo",
      "category": "combo",
      "price": 205,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "palabok"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-w-fries-drink",
      "chain_id": "jollibee",
      "name": "1 – piece. Chickenjoy w/ Fries & drink",
      "category": "combo",
      "price": 156,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-w-fries-solo",
      "chain_id": "jollibee",
      "name": "1 – piece. Chickenjoy w/ Fries Solo",
      "category": "combo",
      "price": 128,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-w-double-rice-regular-iced-tea",
      "chain_id": "jollibee",
      "name": "1-piece. Chickenjoy w/ Double Rice & Regular Iced Tea",
      "category": "combo",
      "price": 143,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 2,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-2-piece-chickenjoy-solo",
      "chain_id": "jollibee",
      "name": "2 – piece. Chickenjoy Solo",
      "category": "main",
      "price": 169,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-2-piece-chickenjoy-w-drink",
      "chain_id": "jollibee",
      "name": "2 – piece. Chickenjoy w/ drink",
      "category": "combo",
      "price": 196,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-jolly-spaghetti-w-drink",
      "chain_id": "jollibee",
      "name": "1 – piece. Chickenjoy & Jolly Spaghetti w/ drink",
      "category": "combo",
      "price": 172,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-jolly-spaghetti-solo",
      "chain_id": "jollibee",
      "name": "1 – piece. Chickenjoy & Jolly Spaghetti Solo",
      "category": "combo",
      "price": 135,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-drink",
      "chain_id": "jollibee",
      "name": "1 – piece. Chickenjoy & drink",
      "category": "combo",
      "price": 105,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-6-piece-chickenjoy-bucket",
      "chain_id": "jollibee",
      "name": "6 Piece Chickenjoy Bucket",
      "category": "main",
      "price": 467,
      "serves": 6,
      "main_servings": 6,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-8-piece-chickenjoy-bucket",
      "chain_id": "jollibee",
      "name": "8 Piece Chickenjoy Bucket",
      "category": "main",
      "price": 573,
      "serves": 8,
      "main_servings": 8,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-12-piece-chickenjoy-bucket",
      "chain_id": "jollibee",
      "name": "12 Piece Chickenjoy Bucket",
      "category": "main",
      "price": 860,
      "serves": 12,
      "main_servings": 12,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-6piece-chickenjoy-w-3-rice-3-sides-3-pies-3-drinks",
      "chain_id": "jollibee",
      "name": "6piece Chickenjoy w/ 3 Rice, 3 Sides, 3 Pies, 3 Drinks",
      "category": "combo",
      "price": 799,
      "serves": 6,
      "main_servings": 6,
      "carb_servings": 3,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-8piece-chickenjoy-w-4-rice-4-sides-4-pies-4-drinks",
      "chain_id": "jollibee",
      "name": "8piece Chickenjoy w/ 4 Rice, 4 Sides, 4 Pies, 4 Drinks",
      "category": "combo",
      "price": 999,
      "serves": 8,
      "main_servings": 8,
      "carb_servings": 4,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-10piece-chickenjoy-w-5-rice-5-sides-5-pies-5-drinks",
      "chain_id": "jollibee",
      "name": "10piece Chickenjoy w/ 5 Rice, 5 Sides, 5 Pies, 5 Drinks",
      "category": "combo",
      "price": 1199,
      "serves": 10,
      "main_servings": 10,
      "carb_servings": 5,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-6piece-chickenjoy-w-jolly-spaghetti-family-pack-3-drinks",
      "chain_id": "jollibee",
      "name": "6piece Chickenjoy w/ Jolly Spaghetti Family Pack, 3 Drinks",
      "category": "combo",
      "price": 850,
      "serves": 6,
      "main_servings": 6,
      "carb_servings": 1,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-10piece-chickenjoy-w-5-peach-mango-pie-5-rice-5-drinks",
      "chain_id": "jollibee",
      "name": "10piece Chickenjoy w/ 5 Peach Mango Pie, 5 Rice, 5 Drinks",
      "category": "combo",
      "price": 1299,
      "serves": 10,
      "main_servings": 10,
      "carb_servings": 5,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "dessert"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-8piece-chickenjoy-w-palabok-fiesta-family-pack-4-drinks",
      "chain_id": "jollibee",
      "name": "8piece Chickenjoy w/ Palabok Fiesta Family Pack, 4 Drinks",
      "category": "combo",
      "price": 1100,
      "serves": 8,
      "main_servings": 8,
      "carb_servings": 1,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "palabok"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-yumburger-solo",
      "chain_id": "jollibee",
      "name": "Yumburger Solo",
      "category": "main",
      "price": 40,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-yumburger-w-drink",
      "chain_id": "jollibee",
      "name": "Yumburger w/ Drink",
      "category": "combo",
      "price": 72,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-yumburger-fries-w-drink",
      "chain_id": "jollibee",
      "name": "Yumburger & Fries w/ Drink",
      "category": "combo",
      "price": 112,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-cheesy-yumburger-solo",
      "chain_id": "jollibee",
      "name": "Cheesy Yumburger Solo",
      "category": "main",
      "price": 69,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "cheese"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-cheesy-yumburger-w-drink",
      "chain_id": "jollibee",
      "name": "Cheesy Yumburger w/ Drink",
      "category": "combo",
      "price": 98,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "cheese"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-cheesy-yumburger-fries-w-drink",
      "chain_id": "jollibee",
      "name": "Cheesy Yumburger & Fries w/ Drink",
      "category": "combo",
      "price": 138,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "cheese"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-double-cheesy-yumburger",
      "chain_id": "jollibee",
      "name": "Double Cheesy Yumburger",
      "category": "main",
      "price": 132,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "cheese"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-double-cheesy-yumburger-w-drink",
      "chain_id": "jollibee",
      "name": "Double Cheesy Yumburger w/ Drink",
      "category": "combo",
      "price": 174,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "cheese"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-bacon-cheesy-yumburger-solo",
      "chain_id": "jollibee",
      "name": "Bacon Cheesy Yumburger Solo",
      "category": "main",
      "price": 96,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "cheese",
        "bacon"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-bacon-cheesy-yumburger-w-drink",
      "chain_id": "jollibee",
      "name": "Bacon Cheesy Yumburger w/ Drink",
      "category": "combo",
      "price": 125,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "cheese",
        "bacon"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-bacon-cheesy-yumburger-fries-w-drink",
      "chain_id": "jollibee",
      "name": "Bacon Cheesy Yumburger & Fries w/ Drink",
      "category": "combo",
      "price": 165,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "cheese",
        "bacon"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-champ-solo",
      "chain_id": "jollibee",
      "name": "Champ Solo",
      "category": "main",
      "price": 179,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-champ-fries-w-drink",
      "chain_id": "jollibee",
      "name": "Champ & Fries w/ Drink",
      "category": "combo",
      "price": 259,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-champ-jr-solo",
      "chain_id": "jollibee",
      "name": "Champ Jr. Solo",
      "category": "main",
      "price": 105,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-champ-jr-fries-w-drink",
      "chain_id": "jollibee",
      "name": "Champ Jr. Fries w/ Drink",
      "category": "combo",
      "price": 174,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-aloha-champ-solo",
      "chain_id": "jollibee",
      "name": "Aloha Champ Solo",
      "category": "main",
      "price": 246,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-aloha-champ-w-fries-drink",
      "chain_id": "jollibee",
      "name": "Aloha Champ w/ Fries & Drink",
      "category": "combo",
      "price": 315,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-amazing-aloha-champ-jr",
      "chain_id": "jollibee",
      "name": "Amazing Aloha Champ Jr",
      "category": "main",
      "price": 125,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "bacon"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-amazing-aloha-champ-jr-w-drink",
      "chain_id": "jollibee",
      "name": "Amazing Aloha Champ Jr. w/ Drink",
      "category": "combo",
      "price": 154,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "bacon"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-amazing-aloha-champ-jr-fries-w-drink",
      "chain_id": "jollibee",
      "name": "Amazing Aloha Champ Jr. Fries w/ Drink",
      "category": "combo",
      "price": 193,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "bacon"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-amazing-aloha-champ-jr-w-o-bacon",
      "chain_id": "jollibee",
      "name": "Amazing Aloha Champ Jr. w/o Bacon",
      "category": "main",
      "price": 122,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-amazing-aloha-champ-jr-w-o-bacon-w-drink",
      "chain_id": "jollibee",
      "name": "Amazing Aloha Champ Jr. w/o Bacon w/ Drink",
      "category": "combo",
      "price": 151,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-double-amazing-aloha-champ-jr",
      "chain_id": "jollibee",
      "name": "Double Amazing Aloha Champ Jr.",
      "category": "main",
      "price": 170,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "bacon"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-double-amazing-aloha-champ-jr-w-drink",
      "chain_id": "jollibee",
      "name": "Double Amazing Aloha Champ Jr. w/ Drink",
      "category": "combo",
      "price": 199,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "bacon"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-double-amazing-aloha-champ-jr-fries-w-drink",
      "chain_id": "jollibee",
      "name": "Double Amazing Aloha Champ Jr. & Fries w/ Drink",
      "category": "combo",
      "price": 239,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "bacon"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-double-amazing-aloha-champ-jr-w-o-bacon",
      "chain_id": "jollibee",
      "name": "Double Amazing Aloha Champ Jr. w/o Bacon",
      "category": "main",
      "price": 159,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-double-amazing-aloha-champ-jr-w-o-bacon-fries-w-drink",
      "chain_id": "jollibee",
      "name": "Double Amazing Aloha Champ Jr. w/o Bacon & Fries w/ Drink",
      "category": "combo",
      "price": 228,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-3-cheesy-yumburgers-w-3-jolly-crispy-fries",
      "chain_id": "jollibee",
      "name": "3 Cheesy Yumburgers w/ 3 Jolly Crispy Fries",
      "category": "combo",
      "price": 276,
      "serves": 3,
      "main_servings": 3,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-3-burgers-3-regular-fries-w-3-drinks",
      "chain_id": "jollibee",
      "name": "3 Burgers & 3 Regular Fries w/ 3 Drinks",
      "category": "combo",
      "price": 382,
      "serves": 3,
      "main_servings": 3,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-burger-steak-solo",
      "chain_id": "jollibee",
      "name": "Burger Steak Solo",
      "category": "main",
      "price": 90,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "burger steak"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-burger-steak-w-drink",
      "chain_id": "jollibee",
      "name": "Burger Steak w/ Drink",
      "category": "combo",
      "price": 120,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "burger steak"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-6-piece-chicken-nuggets-solo",
      "chain_id": "jollibee",
      "name": "6 Piece Chicken Nuggets Solo",
      "category": "main",
      "price": 105,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "nuggets"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-6-piece-chicken-nuggets-fries-w-drink",
      "chain_id": "jollibee",
      "name": "6 Piece Chicken Nuggets & Fries w/ Drink",
      "category": "combo",
      "price": 169,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "nuggets"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-10-piece-chicken-nuggets",
      "chain_id": "jollibee",
      "name": "10 Piece Chicken Nuggets",
      "category": "main",
      "price": 186,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "nuggets"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-4-piece-chicken-nuggets-kiddie-meal",
      "chain_id": "jollibee",
      "name": "4 Piece Chicken Nuggets Kiddie Meal",
      "category": "main",
      "price": 120,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "nuggets",
        "kids"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-4-piece-chicken-nuggets-w-drink-kiddie-meal",
      "chain_id": "jollibee",
      "name": "4 Piece Chicken Nuggets w/ Drink Kiddie Meal",
      "category": "combo",
      "price": 146,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "nuggets",
        "kids"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-8-piece-chicken-nuggets-spicy-dip-solo",
      "chain_id": "jollibee",
      "name": "8 Piece Chicken Nuggets & Spicy Dip Solo",
      "category": "main",
      "price": 149,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "nuggets",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-12-piece-chicken-nuggets-family-pack",
      "chain_id": "jollibee",
      "name": "12 Piece Chicken Nuggets Family Pack",
      "category": "main",
      "price": 225,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "nuggets"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-8-piece-chicken-nuggets-fries-w-drink",
      "chain_id": "jollibee",
      "name": "8 Piece Chicken Nuggets & Fries w/ Drink",
      "category": "combo",
      "price": 199,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "nuggets"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-palabok-fiesta-family-pan",
      "chain_id": "jollibee",
      "name": "Palabok Fiesta Family Pan",
      "category": "side",
      "price": 399,
      "serves": 6,
      "main_servings": 0,
      "carb_servings": 6,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "palabok"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-jolly-spaghetti-family-pan",
      "chain_id": "jollibee",
      "name": "Jolly Spaghetti Family Pan",
      "category": "side",
      "price": 320,
      "serves": 6,
      "main_servings": 0,
      "carb_servings": 6,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-8-piece-chickenjoy-bucket-solo",
      "chain_id": "jollibee",
      "name": "8 Piece Chickenjoy Bucket Solo",
      "category": "main",
      "price": 549,
      "serves": 8,
      "main_servings": 8,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-6-piece-chickenjoy-bucket-solo",
      "chain_id": "jollibee",
      "name": "6 Piece Chickenjoy Bucket Solo",
      "category": "main",
      "price": 449,
      "serves": 6,
      "main_servings": 6,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-palabok-family-pan",
      "chain_id": "jollibee",
      "name": "Palabok Family Pan",
      "category": "side",
      "price": 320,
      "serves": 6,
      "main_servings": 0,
      "carb_servings": 6,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "palabok"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-8-piece-burger-steak-jolly-spaghetti-family-pan",
      "chain_id": "jollibee",
      "name": "8 Piece Burger Steak & Jolly Spaghetti Family Pan",
      "category": "combo",
      "price": 650,
      "serves": 8,
      "main_servings": 8,
      "carb_servings": 8,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "burger steak",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-6-piece-burger-steak-jolly-spaghetti-family-pan",
      "chain_id": "jollibee",
      "name": "6 Piece Burger Steak & Jolly Spaghetti Family Pan",
      "category": "combo",
      "price": 570,
      "serves": 6,
      "main_servings": 6,
      "carb_servings": 6,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "burger steak",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-8-piece-burger-steak-family-pan",
      "chain_id": "jollibee",
      "name": "8 Piece Burger Steak Family Pan",
      "category": "main",
      "price": 470,
      "serves": 8,
      "main_servings": 8,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "burger steak"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-6-piece-burger-steak-family-pan",
      "chain_id": "jollibee",
      "name": "6 Piece Burger Steak Family Pan",
      "category": "main",
      "price": 355,
      "serves": 6,
      "main_servings": 6,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "burger steak"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-4-piece-chickenjoy-family-box-solo-2",
      "chain_id": "jollibee",
      "name": "4 Piece Chickenjoy Family Box Solo",
      "category": "main",
      "price": 326,
      "serves": 4,
      "main_servings": 4,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-3-piece-burger-steak-3-peach-mango-pies",
      "chain_id": "jollibee",
      "name": "3 Piece Burger Steak & 3 Peach Mango Pies",
      "category": "combo",
      "price": 329,
      "serves": 3,
      "main_servings": 3,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "burger steak",
        "dessert"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-3-piece-yumburger-w-3-regular-fries",
      "chain_id": "jollibee",
      "name": "3 Piece Yumburger w/ 3 Regular Fries",
      "category": "combo",
      "price": 276,
      "serves": 3,
      "main_servings": 3,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-3-piece-cheesy-yumburger-3-regular-fries",
      "chain_id": "jollibee",
      "name": "3 Piece Cheesy Yumburger & 3 Regular Fries",
      "category": "combo",
      "price": 340,
      "serves": 3,
      "main_servings": 3,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "cheese"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-sweet-6-pies-to-go",
      "chain_id": "jollibee",
      "name": "Sweet 6 Pies To-Go",
      "category": "dessert",
      "price": 261,
      "serves": 6,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "dessert",
        "pie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-jolly-crispy-fries-bucket",
      "chain_id": "jollibee",
      "name": "Jolly Crispy Fries Bucket",
      "category": "side",
      "price": 165,
      "serves": 6,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-chicken-sandwich-supreme-fries-w-drink",
      "chain_id": "jollibee",
      "name": "Chicken Sandwich Supreme & Fries w/ Drink",
      "category": "combo",
      "price": 227,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "sandwich"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-chicken-sandwich-supreme-solo",
      "chain_id": "jollibee",
      "name": "Chicken Sandwich Supreme Solo",
      "category": "main",
      "price": 149,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "sandwich"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-crispy-chicken-sandwich-fries-w-drink",
      "chain_id": "jollibee",
      "name": "Crispy Chicken Sandwich & Fries w/ Drink",
      "category": "combo",
      "price": 127,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "sandwich"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-crispy-chicken-sandwich-w-drink",
      "chain_id": "jollibee",
      "name": "Crispy Chicken Sandwich w/ Drink",
      "category": "combo",
      "price": 95,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "sandwich"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-crispy-chicken-sandwich-solo",
      "chain_id": "jollibee",
      "name": "Crispy Chicken Sandwich Solo",
      "category": "main",
      "price": 59,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "sandwich"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-spicy-chicken-sandwich-solo",
      "chain_id": "jollibee",
      "name": "Spicy Chicken Sandwich Solo",
      "category": "main",
      "price": 65,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "sandwich",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-spicy-chicken-sandwich-w-drink",
      "chain_id": "jollibee",
      "name": "Spicy Chicken Sandwich w/ Drink",
      "category": "combo",
      "price": 100,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "sandwich",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-bbq-chicken-sandwich-solo",
      "chain_id": "jollibee",
      "name": "BBQ Chicken Sandwich Solo",
      "category": "main",
      "price": 75,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "sandwich",
        "bbq"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-bbq-chicken-sandwich-fries-w-drink",
      "chain_id": "jollibee",
      "name": "BBQ Chicken Sandwich & Fries w/ Drink",
      "category": "combo",
      "price": 130,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "sandwich",
        "bbq"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-pancake-sandwich-solo",
      "chain_id": "jollibee",
      "name": "Pancake Sandwich Solo",
      "category": "main",
      "price": 50,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "pancake"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-pancake-sandwich-w-drink",
      "chain_id": "jollibee",
      "name": "Pancake Sandwich w/ Drink",
      "category": "combo",
      "price": 75,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "pancake"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-jolly-spaghetti-solo",
      "chain_id": "jollibee",
      "name": "Jolly Spaghetti Solo",
      "category": "main",
      "price": 60,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-jolly-spaghetti-w-drink",
      "chain_id": "jollibee",
      "name": "Jolly Spaghetti w/ Drink",
      "category": "combo",
      "price": 93,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-jolly-spaghetti-fries-w-drink",
      "chain_id": "jollibee",
      "name": "Jolly Spaghetti & Fries w/ Drink",
      "category": "combo",
      "price": 144,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-jolly-spaghetti-burger-steak",
      "chain_id": "jollibee",
      "name": "Jolly Spaghetti & Burger Steak",
      "category": "combo",
      "price": 110,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spaghetti",
        "burger steak"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-jolly-spaghetti-yumburger-w-drink",
      "chain_id": "jollibee",
      "name": "Jolly Spaghetti & Yumburger w/ Drink",
      "category": "combo",
      "price": 122,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spaghetti",
        "beef",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-regular-fries-half-jolly-spaghetti-w-drink-super-meal",
      "chain_id": "jollibee",
      "name": "1 Piece Chickenjoy & Regular Fries, Half Jolly Spaghetti, w/ Drink Super Meal",
      "category": "combo",
      "price": 191,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-1-piece-chickenjoy-burger-steak-half-jolly-spaghetti-w-drink-super-meal",
      "chain_id": "jollibee",
      "name": "1 Piece Chickenjoy & Burger Steak, Half Jolly Spaghetti, w/ Drink Super Meal",
      "category": "combo",
      "price": 212,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "burger steak",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-yumburger-half-jolly-spaghetti-regular-fries-w-drink-super-meal",
      "chain_id": "jollibee",
      "name": "Yumburger, Half Jolly Spaghetti, Regular Fries, w/ Drink Super Meal",
      "category": "combo",
      "price": 137,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef",
        "burger",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-burger-steak-half-jolly-spaghetti-w-drink-super-meal",
      "chain_id": "jollibee",
      "name": "Burger Steak, Half Jolly Spaghetti, w/ Drink Super Meal",
      "category": "combo",
      "price": 180,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "burger steak",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-small-chocolate-sundae",
      "chain_id": "jollibee",
      "name": "Small Chocolate Sundae",
      "category": "dessert",
      "price": 27,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "dessert",
        "ice cream"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-chocolate-sundae",
      "chain_id": "jollibee",
      "name": "Chocolate Sundae",
      "category": "dessert",
      "price": 52,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "dessert",
        "ice cream"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-peach-mango-pie",
      "chain_id": "jollibee",
      "name": "Peach Mango Pie",
      "category": "dessert",
      "price": 43,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "dessert",
        "pie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-large-peach-mango-pie",
      "chain_id": "jollibee",
      "name": "Large Peach Mango Pie",
      "category": "dessert",
      "price": 66,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "dessert",
        "pie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-large-peach-mango-pie-3-pies-to-go",
      "chain_id": "jollibee",
      "name": "Large Peach Mango Pie 3 Pies To-Go",
      "category": "dessert",
      "price": 186,
      "serves": 3,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "dessert",
        "pie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-peach-mango-3-pies-to-go",
      "chain_id": "jollibee",
      "name": "Peach Mango 3 Pies To-Go",
      "category": "dessert",
      "price": 338,
      "serves": 3,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "dessert",
        "pie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-peach-mango-6-pies-to-go",
      "chain_id": "jollibee",
      "name": "Peach Mango 6 Pies To-Go",
      "category": "dessert",
      "price": 239,
      "serves": 6,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "dessert",
        "pie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-cookies-cream-sundae",
      "chain_id": "jollibee",
      "name": "Cookies & Cream Sundae",
      "category": "dessert",
      "price": 59,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "dessert",
        "ice cream"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-choco-mallow-pie-6-pies-to-go",
      "chain_id": "jollibee",
      "name": "Choco Mallow Pie 6 Pies To-Go",
      "category": "dessert",
      "price": 303,
      "serves": 6,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "dessert",
        "pie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-ube-cheese-pie",
      "chain_id": "jollibee",
      "name": "Ube Cheese Pie",
      "category": "dessert",
      "price": 50,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "dessert",
        "pie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-ube-cheese-pie-3-pies-to-go",
      "chain_id": "jollibee",
      "name": "Ube Cheese Pie 3 Pies To-Go",
      "category": "dessert",
      "price": 144,
      "serves": 3,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "dessert",
        "pie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-ube-cheese-pie-6-pies-to-go",
      "chain_id": "jollibee",
      "name": "Ube Cheese Pie 6 Pies To-Go",
      "category": "dessert",
      "price": 287,
      "serves": 6,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "dessert",
        "pie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-buko-pandan-sundae",
      "chain_id": "jollibee",
      "name": "Buko Pandan Sundae",
      "category": "dessert",
      "price": 63,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "dessert",
        "ice cream"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-choco-banana-1-pie",
      "chain_id": "jollibee",
      "name": "Choco Banana 1 Pie",
      "category": "dessert",
      "price": 50,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "dessert",
        "pie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-choco-banana-3-pies-to-go",
      "chain_id": "jollibee",
      "name": "Choco Banana 3 Pies To-Go",
      "category": "dessert",
      "price": 142,
      "serves": 3,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "dessert",
        "pie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-choco-banana-6-pies-to-go",
      "chain_id": "jollibee",
      "name": "Choco Banana 6 Pies To-Go",
      "category": "dessert",
      "price": 286,
      "serves": 6,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "dessert",
        "pie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-cookie-caramel-sundae",
      "chain_id": "jollibee",
      "name": "Cookie Caramel Sundae",
      "category": "dessert",
      "price": 63,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "dessert",
        "ice cream"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-choco-graham-fudge-sundae",
      "chain_id": "jollibee",
      "name": "Choco Graham Fudge Sundae",
      "category": "dessert",
      "price": 63,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "dessert",
        "ice cream"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-longganisa-solo",
      "chain_id": "jollibee",
      "name": "Longganisa Solo",
      "category": "main",
      "price": 165,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-longganisa-w-drink",
      "chain_id": "jollibee",
      "name": "Longganisa w/ Drink",
      "category": "combo",
      "price": 193,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-beef-tapa-solo",
      "chain_id": "jollibee",
      "name": "Beef Tapa Solo",
      "category": "main",
      "price": 165,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "beef"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-beef-tapa-w-drink",
      "chain_id": "jollibee",
      "name": "Beef Tapa w/ Drink",
      "category": "combo",
      "price": 193,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "beef"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-corned-beef-solo",
      "chain_id": "jollibee",
      "name": "Corned Beef Solo",
      "category": "main",
      "price": 165,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "beef"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-corned-beef-w-drink",
      "chain_id": "jollibee",
      "name": "Corned Beef w/ Drink",
      "category": "combo",
      "price": 193,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "beef"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-breakfast-chickenjoy-solo",
      "chain_id": "jollibee",
      "name": "Breakfast Chickenjoy Solo",
      "category": "main",
      "price": 148,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-breakfast-chickenjoy-w-drink",
      "chain_id": "jollibee",
      "name": "Breakfast Chickenjoy w/ Drink",
      "category": "combo",
      "price": 176,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-breakfast-burger-steak-solo",
      "chain_id": "jollibee",
      "name": "Breakfast Burger Steak Solo",
      "category": "main",
      "price": 127,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "burger steak"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-breakfast-burger-steak-w-drink",
      "chain_id": "jollibee",
      "name": "Breakfast Burger Steak w/ Drink",
      "category": "combo",
      "price": 155,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "burger steak"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-2-pancakes-solo",
      "chain_id": "jollibee",
      "name": "2 Pancakes Solo",
      "category": "main",
      "price": 82,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "pancake"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-2-pancakes-w-drink",
      "chain_id": "jollibee",
      "name": "2 Pancakes w/ Drink",
      "category": "combo",
      "price": 111,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "pancake"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-bacon-egg-cheese-pancake-sandwich-solo",
      "chain_id": "jollibee",
      "name": "Bacon, Egg, & Cheese Pancake Sandwich Solo",
      "category": "main",
      "price": 100,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "bacon",
        "egg",
        "cheese"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-bacon-egg-cheese-pancake-sandwich-w-drink",
      "chain_id": "jollibee",
      "name": "Bacon, Egg, & Cheese Pancake Sandwich w/ Drink",
      "category": "combo",
      "price": 129,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "bacon",
        "egg",
        "cheese"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-bacon-egg-cheese-sandwich-solo",
      "chain_id": "jollibee",
      "name": "Bacon, Egg, & Cheese Sandwich Solo",
      "category": "main",
      "price": 95,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "bacon",
        "egg",
        "cheese"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-bacon-egg-cheese-sandwich-w-drink",
      "chain_id": "jollibee",
      "name": "Bacon, Egg, & Cheese Sandwich w/ Drink",
      "category": "combo",
      "price": 123,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "bacon",
        "egg",
        "cheese"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-breakfast-hotdog-solo",
      "chain_id": "jollibee",
      "name": "Breakfast Hotdog Solo",
      "category": "main",
      "price": 122,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "hotdog"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-breakfast-hotdog-w-drink",
      "chain_id": "jollibee",
      "name": "Breakfast Hotdog w/ Drink",
      "category": "combo",
      "price": 151,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "hotdog"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-breakfast-wrap-solo",
      "chain_id": "jollibee",
      "name": "Breakfast Wrap Solo",
      "category": "main",
      "price": 135,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "wrap"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-breakfast-wrap-w-drink",
      "chain_id": "jollibee",
      "name": "Breakfast Wrap w/ Drink",
      "category": "combo",
      "price": 163,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "wrap"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-chicken-sausage-pancakes-solo",
      "chain_id": "jollibee",
      "name": "Chicken Sausage & Pancakes Solo",
      "category": "main",
      "price": 115,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "chicken",
        "pancake"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-chicken-sausage-pancakes-w-drink",
      "chain_id": "jollibee",
      "name": "Chicken Sausage & Pancakes w/ Drink",
      "category": "combo",
      "price": 143,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "chicken",
        "pancake"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-chicken-tocino-solo",
      "chain_id": "jollibee",
      "name": "Chicken Tocino Solo",
      "category": "main",
      "price": 165,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "jb-chicken-tocino-w-drink",
      "chain_id": "jollibee",
      "name": "Chicken Tocino w/ Drink",
      "category": "combo",
      "price": 193,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "breakfast",
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    }
  ]
};
