// AUTO-GENERATED by scripts/pipeline (ROADMAP.md Milestone 4) — do not hand-edit.
// To fix a specific item, add/update it in data/overrides/mang-inasal.json instead;
// re-running the pipeline preserves override entries (DATA-PIPELINE.md §2).
// Last pipeline run: 2026-08-11. Source: https://www.manginasal.ph/news/menu-and-prices (official).

import type { ChainData } from "../types.js";

export const mangInasal: ChainData = {
  "chain": {
    "id": "mang-inasal",
    "name": "Mang Inasal",
    "source_url": "https://www.manginasal.ph/news/menu-and-prices",
    "source_type": "official",
    "last_updated": "2026-08-11",
    "notes": "NCR reference pricing; unlimited rice modeled as near-zero-price high-carb_servings item (DATA-MODEL.md §4)."
  },
  "items": [
    {
      "id": "mi-paa-large-1-rice",
      "chain_id": "mang-inasal",
      "name": "Paa Large 1 Rice",
      "category": "main",
      "price": 135,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-large-1-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "Paa Large 1 Rice Value Meal",
      "category": "main",
      "price": 165,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-large-unli-rice",
      "chain_id": "mang-inasal",
      "name": "Paa Large Unli Rice",
      "category": "main",
      "price": 175,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-large-unli-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "Paa Large Unli Rice Value Meal",
      "category": "main",
      "price": 205,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-spicy-paa-large-1-rice",
      "chain_id": "mang-inasal",
      "name": "Spicy Paa Large 1 Rice",
      "category": "main",
      "price": 150,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-spicy-paa-large-1-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "Spicy Paa Large 1 Rice Value Meal",
      "category": "main",
      "price": 180,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-spicy-paa-large-unli-rice",
      "chain_id": "mang-inasal",
      "name": "Spicy Paa Large Unli Rice",
      "category": "main",
      "price": 190,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-spicy-paa-large-unli-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "Spicy Paa Large Unli Rice Value Meal",
      "category": "main",
      "price": 220,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-large-1-rice",
      "chain_id": "mang-inasal",
      "name": "Pecho Large 1 Rice",
      "category": "main",
      "price": 165,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-large-1-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "Pecho Large 1 Rice Value Meal",
      "category": "main",
      "price": 195,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-large-unli-rice",
      "chain_id": "mang-inasal",
      "name": "Pecho Large Unli Rice",
      "category": "main",
      "price": 205,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-large-unli-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "Pecho Large Unli Rice Value Meal",
      "category": "main",
      "price": 235,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-spicy-pecho-large-1-rice",
      "chain_id": "mang-inasal",
      "name": "Spicy Pecho Large 1 Rice",
      "category": "main",
      "price": 180,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-spicy-pecho-large-1-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "Spicy Pecho Large 1 Rice Value Meal",
      "category": "main",
      "price": 210,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-spicy-pecho-large-unli-rice",
      "chain_id": "mang-inasal",
      "name": "Spicy Pecho Large Unli Rice",
      "category": "main",
      "price": 220,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-spicy-pecho-large-unli-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "Spicy Pecho Large Unli Rice Value Meal",
      "category": "main",
      "price": 250,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-regular-chicken-1-rice",
      "chain_id": "mang-inasal",
      "name": "Regular Chicken 1 Rice",
      "category": "main",
      "price": 99,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-regular-chicken-1-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "Regular Chicken 1 Rice Value Meal",
      "category": "main",
      "price": 129,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-regular-chicken-unli-rice",
      "chain_id": "mang-inasal",
      "name": "Regular Chicken Unli Rice",
      "category": "main",
      "price": 139,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-regular-chicken-unli-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "Regular Chicken Unli Rice Value Meal",
      "category": "main",
      "price": 169,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-1pc-pork-bbq-ala-carte",
      "chain_id": "mang-inasal",
      "name": "1pc Pork BBQ Ala Carte",
      "category": "main",
      "price": 50,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-1pc-pork-bbq-with-vinegar-solo",
      "chain_id": "mang-inasal",
      "name": "1pc Pork BBQ With Vinegar Solo",
      "category": "main",
      "price": 59,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-1pc-pork-bbq-with-vinegar-value-meal",
      "chain_id": "mang-inasal",
      "name": "1pc Pork BBQ With Vinegar Value Meal",
      "category": "main",
      "price": 89,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-pork-bbq-value-meal",
      "chain_id": "mang-inasal",
      "name": "2pc Pork BBQ Value Meal",
      "category": "main",
      "price": 129,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-pork-bbq-ur-solo",
      "chain_id": "mang-inasal",
      "name": "2pc Pork BBQ UR Solo",
      "category": "main",
      "price": 139,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-pork-bbq-ur-value-meal",
      "chain_id": "mang-inasal",
      "name": "2pc Pork BBQ UR Value Meal",
      "category": "main",
      "price": 169,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-buddy-size-4pcs",
      "chain_id": "mang-inasal",
      "name": "Buddy Size 4pcs",
      "category": "main",
      "price": 193,
      "serves": 2,
      "main_servings": 4,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-family-size-10pcs",
      "chain_id": "mang-inasal",
      "name": "Family Size 10pcs",
      "category": "main",
      "price": 475,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-party-size-20pcs",
      "chain_id": "mang-inasal",
      "name": "Party Size 20pcs",
      "category": "main",
      "price": 950,
      "serves": 10,
      "main_servings": 20,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-pork-bbq-with-peanut-sauce-java-rice",
      "chain_id": "mang-inasal",
      "name": "2pc Pork BBQ With Peanut Sauce & Java Rice",
      "category": "main",
      "price": 135,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-pork-bbq-with-peanut-sauce-java-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "2pc Pork BBQ With Peanut Sauce & Java Rice Value Meal",
      "category": "main",
      "price": 165,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-1pc-spicy-pork-bbq-ala-carte",
      "chain_id": "mang-inasal",
      "name": "1pc Spicy Pork BBQ Ala Carte",
      "category": "main",
      "price": 55,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-1pc-spicy-pork-bbq-with-vinegar-solo",
      "chain_id": "mang-inasal",
      "name": "1pc Spicy Pork BBQ With Vinegar Solo",
      "category": "main",
      "price": 64,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-1pc-spicy-pork-bbq-with-vinegar-value-meal",
      "chain_id": "mang-inasal",
      "name": "1pc Spicy Pork BBQ With Vinegar Value Meal",
      "category": "main",
      "price": 94,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-spicy-pork-bbq-value-meal",
      "chain_id": "mang-inasal",
      "name": "2pc Spicy Pork BBQ Value Meal",
      "category": "main",
      "price": 139,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-spicy-pork-bbq-ur-solo",
      "chain_id": "mang-inasal",
      "name": "2pc Spicy Pork BBQ UR Solo",
      "category": "main",
      "price": 149,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-spicy-pork-bbq-ur-value-meal",
      "chain_id": "mang-inasal",
      "name": "2pc Spicy Pork BBQ UR Value Meal",
      "category": "main",
      "price": 179,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-buddy-size-4pcs-2",
      "chain_id": "mang-inasal",
      "name": "Buddy Size 4pcs",
      "category": "main",
      "price": 205,
      "serves": 2,
      "main_servings": 4,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "pork",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-family-size-10pcs-2",
      "chain_id": "mang-inasal",
      "name": "Family Size 10pcs",
      "category": "main",
      "price": 505,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "pork",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-party-size-20pcs-2",
      "chain_id": "mang-inasal",
      "name": "Party Size 20pcs",
      "category": "main",
      "price": 999,
      "serves": 10,
      "main_servings": 20,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "pork",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-spicy-pork-bbq-with-peanut-sauce-java-rice",
      "chain_id": "mang-inasal",
      "name": "2pc Spicy Pork BBQ With Peanut Sauce & Java Rice",
      "category": "main",
      "price": 145,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-spicy-pork-bbq-with-peanut-sauce-java-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "2pc Spicy Pork BBQ With Peanut Sauce & Java Rice Value Meal",
      "category": "main",
      "price": 175,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-1pc-chicken-bbq-ala-carte",
      "chain_id": "mang-inasal",
      "name": "1pc Chicken BBQ Ala Carte",
      "category": "main",
      "price": 50,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-1pc-chicken-bbq-with-vinegar-solo",
      "chain_id": "mang-inasal",
      "name": "1pc Chicken BBQ With Vinegar Solo",
      "category": "main",
      "price": 59,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-1pc-chicken-bbq-with-vinegar-value-meal",
      "chain_id": "mang-inasal",
      "name": "1pc Chicken BBQ With Vinegar Value Meal",
      "category": "main",
      "price": 89,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-chicken-bbq-value-meal",
      "chain_id": "mang-inasal",
      "name": "2pc Chicken BBQ Value Meal",
      "category": "main",
      "price": 129,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-chicken-bbq-ur-solo",
      "chain_id": "mang-inasal",
      "name": "2pc Chicken BBQ UR Solo",
      "category": "main",
      "price": 139,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-chicken-bbq-ur-value-meal",
      "chain_id": "mang-inasal",
      "name": "2pc Chicken BBQ UR Value Meal",
      "category": "main",
      "price": 169,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-family-size-10pcs-3",
      "chain_id": "mang-inasal",
      "name": "Family Size 10pcs",
      "category": "main",
      "price": 475,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-chicken-bbq-with-peanut-sauce-java-rice",
      "chain_id": "mang-inasal",
      "name": "2pc Chicken BBQ With Peanut Sauce & Java Rice",
      "category": "main",
      "price": 135,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-chicken-bbq-with-peanut-sauce-java-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "2pc Chicken BBQ With Peanut Sauce & Java Rice Value Meal",
      "category": "main",
      "price": 165,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-1pc-spicy-chicken-bbq-ala-carte",
      "chain_id": "mang-inasal",
      "name": "1pc Spicy Chicken BBQ Ala Carte",
      "category": "main",
      "price": 55,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-1pc-spicy-chicken-bbq-with-vinegar-solo",
      "chain_id": "mang-inasal",
      "name": "1pc Spicy Chicken BBQ With Vinegar Solo",
      "category": "main",
      "price": 64,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-1pc-spicy-chicken-bbq-with-vinegar-value-meal",
      "chain_id": "mang-inasal",
      "name": "1pc Spicy Chicken BBQ With Vinegar Value Meal",
      "category": "main",
      "price": 94,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-spicy-chicken-bbq-value-meal",
      "chain_id": "mang-inasal",
      "name": "2pc Spicy Chicken BBQ Value Meal",
      "category": "main",
      "price": 139,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-spicy-chicken-bbq-ur-solo",
      "chain_id": "mang-inasal",
      "name": "2pc Spicy Chicken BBQ UR Solo",
      "category": "main",
      "price": 149,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-spicy-chicken-bbq-ur-value-meal",
      "chain_id": "mang-inasal",
      "name": "2pc Spicy Chicken BBQ UR Value Meal",
      "category": "main",
      "price": 179,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-family-size-10pcs-4",
      "chain_id": "mang-inasal",
      "name": "Family Size 10pcs",
      "category": "main",
      "price": 505,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-spicy-chicken-bbq-with-peanut-sauce-java-rice",
      "chain_id": "mang-inasal",
      "name": "2pc Spicy Chicken BBQ With Peanut Sauce & Java Rice",
      "category": "main",
      "price": 145,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-spicy-chicken-bbq-with-peanut-sauce-java-rice-value-meal",
      "chain_id": "mang-inasal",
      "name": "2pc Spicy Chicken BBQ With Peanut Sauce & Java Rice Value Meal",
      "category": "main",
      "price": 175,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-liempo-inasal-1-rice",
      "chain_id": "mang-inasal",
      "name": "Liempo Inasal 1 Rice",
      "category": "main",
      "price": 135,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-liempo-inasal-unli-rice",
      "chain_id": "mang-inasal",
      "name": "Liempo Inasal Unli Rice",
      "category": "main",
      "price": 175,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-liempo-buddy-size",
      "chain_id": "mang-inasal",
      "name": "Liempo Buddy Size",
      "category": "main",
      "price": 260,
      "serves": 2,
      "main_servings": 2,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-liempo-family-size",
      "chain_id": "mang-inasal",
      "name": "Liempo Family Size",
      "category": "main",
      "price": 518,
      "serves": 5,
      "main_servings": 5,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pork-sisig-1-rice",
      "chain_id": "mang-inasal",
      "name": "Pork Sisig 1 Rice",
      "category": "main",
      "price": 105,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-chicken-sisig-1-rice",
      "chain_id": "mang-inasal",
      "name": "Chicken Sisig 1 Rice",
      "category": "main",
      "price": 105,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-bangus-sisig-1-rice",
      "chain_id": "mang-inasal",
      "name": "Bangus Sisig 1 Rice",
      "category": "main",
      "price": 135,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "fish"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-extra-creamy-8oz",
      "chain_id": "mang-inasal",
      "name": "Extra Creamy 8oz",
      "category": "dessert",
      "price": 39,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-12oz-small",
      "chain_id": "mang-inasal",
      "name": "12oz Small",
      "category": "dessert",
      "price": 75,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-16oz-regular",
      "chain_id": "mang-inasal",
      "name": "16oz Regular",
      "category": "dessert",
      "price": 95,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-1-rice",
      "chain_id": "mang-inasal",
      "name": "Paa 1 Rice",
      "category": "combo",
      "price": 224,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-unli-rice",
      "chain_id": "mang-inasal",
      "name": "Paa Unli Rice",
      "category": "combo",
      "price": 274,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-1-rice",
      "chain_id": "mang-inasal",
      "name": "Pecho 1 Rice",
      "category": "combo",
      "price": 254,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-unli-rice",
      "chain_id": "mang-inasal",
      "name": "Pecho Unli Rice",
      "category": "combo",
      "price": 304,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-pork-bbq",
      "chain_id": "mang-inasal",
      "name": "Paa + Pork BBQ",
      "category": "combo",
      "price": 254,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-pork-bbq",
      "chain_id": "mang-inasal",
      "name": "Pecho + Pork BBQ",
      "category": "combo",
      "price": 284,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-chicken-bbq",
      "chain_id": "mang-inasal",
      "name": "Paa + Chicken BBQ",
      "category": "combo",
      "price": 254,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-chicken-bbq",
      "chain_id": "mang-inasal",
      "name": "Pecho + Chicken BBQ",
      "category": "combo",
      "price": 284,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-1-rice-2",
      "chain_id": "mang-inasal",
      "name": "Paa 1 Rice",
      "category": "combo",
      "price": 224,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-1-rice-2",
      "chain_id": "mang-inasal",
      "name": "Pecho 1 Rice",
      "category": "combo",
      "price": 254,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-pork-bbq-2",
      "chain_id": "mang-inasal",
      "name": "Paa + Pork BBQ",
      "category": "combo",
      "price": 254,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-pork-bbq-2",
      "chain_id": "mang-inasal",
      "name": "Pecho + Pork BBQ",
      "category": "combo",
      "price": 284,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-all-chicken-inasal-paa",
      "chain_id": "mang-inasal",
      "name": "All Chicken Inasal Paa",
      "category": "combo",
      "price": 895,
      "serves": 5,
      "main_servings": 5,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-all-chicken-inasal-pecho",
      "chain_id": "mang-inasal",
      "name": "All Chicken Inasal Pecho",
      "category": "combo",
      "price": 1075,
      "serves": 5,
      "main_servings": 5,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-ffm-all-chicken-inasal-paa",
      "chain_id": "mang-inasal",
      "name": "FFM All Chicken Inasal Paa",
      "category": "combo",
      "price": 995,
      "serves": 5,
      "main_servings": 5,
      "carb_servings": 1,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-ffm-all-chicken-inasal-pecho",
      "chain_id": "mang-inasal",
      "name": "FFM All Chicken Inasal Pecho",
      "category": "combo",
      "price": 1175,
      "serves": 5,
      "main_servings": 5,
      "carb_servings": 1,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-pork-bbq-3",
      "chain_id": "mang-inasal",
      "name": "Paa & Pork BBQ",
      "category": "combo",
      "price": 765,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-pork-bbq-3",
      "chain_id": "mang-inasal",
      "name": "Pecho & Pork BBQ",
      "category": "combo",
      "price": 855,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-ffm-paa-pork-bbq",
      "chain_id": "mang-inasal",
      "name": "FFM Paa & Pork BBQ",
      "category": "combo",
      "price": 865,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 1,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-ffm-pecho-pork-bbq",
      "chain_id": "mang-inasal",
      "name": "FFM Pecho & Pork BBQ",
      "category": "combo",
      "price": 955,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 1,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-chicken-bbq-2",
      "chain_id": "mang-inasal",
      "name": "Paa & Chicken BBQ",
      "category": "combo",
      "price": 765,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-chicken-bbq-2",
      "chain_id": "mang-inasal",
      "name": "Pecho & Chicken BBQ",
      "category": "combo",
      "price": 855,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-grilled-liempo",
      "chain_id": "mang-inasal",
      "name": "Paa & Grilled Liempo",
      "category": "combo",
      "price": 865,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-grilled-liempo",
      "chain_id": "mang-inasal",
      "name": "Pecho & Grilled Liempo",
      "category": "combo",
      "price": 985,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pork-bbq-grilled-liempo",
      "chain_id": "mang-inasal",
      "name": "Pork BBQ & Grilled Liempo",
      "category": "combo",
      "price": 750,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-chicken-bbq-grilled-liempo",
      "chain_id": "mang-inasal",
      "name": "Chicken BBQ & Grilled Liempo",
      "category": "combo",
      "price": 750,
      "serves": 5,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-1pc",
      "chain_id": "mang-inasal",
      "name": "1pc",
      "category": "side",
      "price": 29,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "vegetable"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pcs",
      "chain_id": "mang-inasal",
      "name": "2pcs",
      "category": "side",
      "price": 55,
      "serves": 2,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "vegetable"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-6pcs",
      "chain_id": "mang-inasal",
      "name": "6pcs",
      "category": "side",
      "price": 165,
      "serves": 6,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "vegetable"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-solo",
      "chain_id": "mang-inasal",
      "name": "Solo",
      "category": "main",
      "price": 89,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "noodles"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-value-meal",
      "chain_id": "mang-inasal",
      "name": "Value Meal",
      "category": "main",
      "price": 119,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "noodles"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-family-size",
      "chain_id": "mang-inasal",
      "name": "Family Size",
      "category": "main",
      "price": 345,
      "serves": 5,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "noodles"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-party-size",
      "chain_id": "mang-inasal",
      "name": "Party Size",
      "category": "main",
      "price": 681,
      "serves": 10,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "noodles"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-solo-2",
      "chain_id": "mang-inasal",
      "name": "Solo",
      "category": "main",
      "price": 89,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "noodles"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-value-meal-2",
      "chain_id": "mang-inasal",
      "name": "Value Meal",
      "category": "main",
      "price": 119,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "noodles"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-family-size-2",
      "chain_id": "mang-inasal",
      "name": "Family Size",
      "category": "main",
      "price": 345,
      "serves": 5,
      "main_servings": 5,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "noodles"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-party-size-2",
      "chain_id": "mang-inasal",
      "name": "Party Size",
      "category": "main",
      "price": 681,
      "serves": 10,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "noodles"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-chicken-inasal",
      "chain_id": "mang-inasal",
      "name": "Chicken Inasal",
      "category": "main",
      "price": 139,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "breakfast"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pork-bbq",
      "chain_id": "mang-inasal",
      "name": "Pork BBQ",
      "category": "main",
      "price": 139,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork",
        "breakfast"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pork-sisig",
      "chain_id": "mang-inasal",
      "name": "Pork Sisig",
      "category": "main",
      "price": 139,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork",
        "breakfast"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-chicken-bbq",
      "chain_id": "mang-inasal",
      "name": "Chicken BBQ",
      "category": "main",
      "price": 139,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "breakfast"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-chicken-sisig",
      "chain_id": "mang-inasal",
      "name": "Chicken Sisig",
      "category": "main",
      "price": 139,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "breakfast"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-soy-garlic-chicken-rice-bowl",
      "chain_id": "mang-inasal",
      "name": "Soy Garlic Chicken Rice Bowl",
      "category": "main",
      "price": 89,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pork-sisig-rice-bowl",
      "chain_id": "mang-inasal",
      "name": "Pork Sisig Rice Bowl",
      "category": "main",
      "price": 89,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-large-halo-halo",
      "chain_id": "mang-inasal",
      "name": "Paa Large + Halo Halo",
      "category": "combo",
      "price": 194,
      "serves": 2,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": true,
      "combo_contents": [
        {
          "item_id": "mi-paa-large-1-rice",
          "qty": 1
        },
        {
          "item_id": "mi-extra-creamy-8oz",
          "qty": 1
        }
      ],
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-large-halo-halo",
      "chain_id": "mang-inasal",
      "name": "Pecho Large + Halo Halo",
      "category": "combo",
      "price": 224,
      "serves": 2,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": true,
      "combo_contents": [
        {
          "item_id": "mi-pecho-large-1-rice",
          "qty": 1
        },
        {
          "item_id": "mi-extra-creamy-8oz",
          "qty": 1
        }
      ],
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-large-unli-rice-halo-halo-8oz",
      "chain_id": "mang-inasal",
      "name": "Pecho Large Unli Rice + Halo Halo 8oz",
      "category": "combo",
      "price": 234,
      "serves": 2,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": true,
      "combo_contents": [
        {
          "item_id": "mi-pecho-large-unli-rice",
          "qty": 1
        },
        {
          "item_id": "mi-extra-creamy-8oz",
          "qty": 1
        }
      ],
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-large-1-rice-value-meal-halo-halo-8oz",
      "chain_id": "mang-inasal",
      "name": "Paa Large 1 Rice Value Meal + Halo Halo 8oz",
      "category": "combo",
      "price": 194,
      "serves": 2,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": true,
      "combo_contents": [
        {
          "item_id": "mi-paa-large-1-rice-value-meal",
          "qty": 1
        },
        {
          "item_id": "mi-extra-creamy-8oz",
          "qty": 1
        }
      ],
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-paa-large-unli-rice-value-meal-halo-halo-8oz",
      "chain_id": "mang-inasal",
      "name": "Paa Large Unli Rice Value Meal + Halo Halo 8oz",
      "category": "combo",
      "price": 234,
      "serves": 2,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": true,
      "combo_contents": [
        {
          "item_id": "mi-paa-large-unli-rice-value-meal",
          "qty": 1
        },
        {
          "item_id": "mi-extra-creamy-8oz",
          "qty": 1
        }
      ],
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-large-1-rice-value-meal-halo-halo-8oz",
      "chain_id": "mang-inasal",
      "name": "Pecho Large 1 Rice Value Meal + Halo Halo 8oz",
      "category": "combo",
      "price": 224,
      "serves": 2,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": true,
      "combo_contents": [
        {
          "item_id": "mi-pecho-large-1-rice-value-meal",
          "qty": 1
        },
        {
          "item_id": "mi-extra-creamy-8oz",
          "qty": 1
        }
      ],
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-pecho-large-unli-rice-value-meal-halo-halo-8oz",
      "chain_id": "mang-inasal",
      "name": "Pecho Large Unli Rice Value Meal + Halo Halo 8oz",
      "category": "combo",
      "price": 264,
      "serves": 2,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": true,
      "combo_contents": [
        {
          "item_id": "mi-pecho-large-unli-rice-value-meal",
          "qty": 1
        },
        {
          "item_id": "mi-extra-creamy-8oz",
          "qty": 1
        }
      ],
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-bbq-vinegar-value-meal-halo-halo-8oz",
      "chain_id": "mang-inasal",
      "name": "2pc BBQ Vinegar Value Meal + Halo Halo 8oz",
      "category": "combo",
      "price": 158,
      "serves": 2,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": true,
      "combo_contents": [
        {
          "item_id": "mi-2pc-pork-bbq-value-meal",
          "qty": 1
        },
        {
          "item_id": "mi-extra-creamy-8oz",
          "qty": 1
        }
      ],
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-bbq-vinegar-ur-value-meal-halo-halo-8oz",
      "chain_id": "mang-inasal",
      "name": "2pc BBQ Vinegar UR Value Meal + Halo Halo 8oz",
      "category": "combo",
      "price": 198,
      "serves": 2,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": true,
      "combo_contents": [
        {
          "item_id": "mi-2pc-pork-bbq-ur-value-meal",
          "qty": 1
        },
        {
          "item_id": "mi-extra-creamy-8oz",
          "qty": 1
        }
      ],
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-pork-bbq-peanut-sauce-value-meal-halo-halo-8oz",
      "chain_id": "mang-inasal",
      "name": "2pc Pork BBQ Peanut Sauce Value Meal + Halo Halo 8oz",
      "category": "combo",
      "price": 194,
      "serves": 2,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": true,
      "combo_contents": [
        {
          "item_id": "mi-2pc-pork-bbq-with-peanut-sauce-java-rice-value-meal",
          "qty": 1
        },
        {
          "item_id": "mi-extra-creamy-8oz",
          "qty": 1
        }
      ],
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-pork-bbq-peanut-sauce-ur-value-meal-halo-halo-8oz",
      "chain_id": "mang-inasal",
      "name": "2pc Pork BBQ Peanut Sauce UR Value Meal + Halo Halo 8oz",
      "category": "combo",
      "price": 244,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pork"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-chicken-bbq-vinegar-value-meal-halo-halo-8oz",
      "chain_id": "mang-inasal",
      "name": "2pc Chicken BBQ Vinegar Value Meal + Halo Halo 8oz",
      "category": "combo",
      "price": 158,
      "serves": 2,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": true,
      "combo_contents": [
        {
          "item_id": "mi-2pc-chicken-bbq-value-meal",
          "qty": 1
        },
        {
          "item_id": "mi-extra-creamy-8oz",
          "qty": 1
        }
      ],
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-chicken-bbq-vinegar-ur-value-meal-halo-halo-8oz",
      "chain_id": "mang-inasal",
      "name": "2pc Chicken BBQ Vinegar UR Value Meal + Halo Halo 8oz",
      "category": "combo",
      "price": 198,
      "serves": 2,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": true,
      "combo_contents": [
        {
          "item_id": "mi-2pc-chicken-bbq-ur-value-meal",
          "qty": 1
        },
        {
          "item_id": "mi-extra-creamy-8oz",
          "qty": 1
        }
      ],
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-chicken-bbq-peanut-sauce-value-meal-halo-halo-8oz",
      "chain_id": "mang-inasal",
      "name": "2pc Chicken BBQ Peanut Sauce Value Meal + Halo Halo 8oz",
      "category": "combo",
      "price": 194,
      "serves": 2,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": true,
      "combo_contents": [
        {
          "item_id": "mi-2pc-chicken-bbq-with-peanut-sauce-java-rice-value-meal",
          "qty": 1
        },
        {
          "item_id": "mi-extra-creamy-8oz",
          "qty": 1
        }
      ],
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-2pc-chicken-bbq-peanut-sauce-ur-value-meal-halo-halo-8oz",
      "chain_id": "mang-inasal",
      "name": "2pc Chicken BBQ Peanut Sauce UR Value Meal + Halo Halo 8oz",
      "category": "combo",
      "price": 244,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mi-unlimited-rice",
      "chain_id": "mang-inasal",
      "name": "Unlimited Rice (per order)",
      "category": "rice",
      "price": 5,
      "serves": 10,
      "main_servings": 0,
      "carb_servings": 10,
      "shareable": true,
      "is_combo": false,
      "tags": [],
      "available": true,
      "price_confidence": "manual-override"
    }
  ]
};
