// AUTO-GENERATED by scripts/pipeline (ROADMAP.md Milestone 4) — do not hand-edit.
// To fix a specific item, add/update it in data/overrides/mcdonalds.json instead;
// re-running the pipeline preserves override entries (DATA-PIPELINE.md §2).
// Last pipeline run: 2026-08-11. Source: https://mcdomenuprices.com.ph/ (third-party-aggregator).

import type { ChainData } from "../types.js";

export const mcdonalds: ChainData = {
  "chain": {
    "id": "mcdonalds",
    "name": "McDonald's",
    "source_url": "https://mcdomenuprices.com.ph/",
    "source_type": "third-party-aggregator",
    "last_updated": "2026-08-11",
    "notes": "Illustrative Milestone-2 dataset — see DATA-PIPELINE.md §1 for the real source plan."
  },
  "items": [
    {
      "id": "mc-taro-custard-pie",
      "chain_id": "mcdonalds",
      "name": "Taro Custard Pie",
      "category": "dessert",
      "price": 51,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "taro",
        "dessert"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-large-poptato",
      "chain_id": "mcdonalds",
      "name": "Large Poptato",
      "category": "side",
      "price": 100,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "poptato",
        "side"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-medium-poptato-with-mcshaker-bbq",
      "chain_id": "mcdonalds",
      "name": "Medium Poptato with McShaker BBQ",
      "category": "side",
      "price": 86,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "poptato",
        "bbq"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-choco-lava-puff",
      "chain_id": "mcdonalds",
      "name": "Choco Lava Puff",
      "category": "dessert",
      "price": 77,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chocolate",
        "dessert"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-crispy-chicken-sandwich-with-poptato-meal",
      "chain_id": "mcdonalds",
      "name": "Crispy Chicken Sandwich with Poptato Meal",
      "category": "combo",
      "price": 143,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "sandwich",
        "poptato",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-matcha-mcflurry-with-oreo-solo",
      "chain_id": "mcdonalds",
      "name": "Matcha McFlurry with Oreo Solo",
      "category": "dessert",
      "price": 83,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "matcha",
        "oreo",
        "flurry"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-ebi-burger-meal",
      "chain_id": "mcdonalds",
      "name": "Ebi Burger Meal",
      "category": "combo",
      "price": 265,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "ebi",
        "burger",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-triple-cheeseburger-meal",
      "chain_id": "mcdonalds",
      "name": "Triple Cheeseburger Meal",
      "category": "combo",
      "price": 290,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cheeseburger",
        "triple",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-double-cheeseburger-meal",
      "chain_id": "mcdonalds",
      "name": "Double Cheeseburger Meal",
      "category": "combo",
      "price": 250,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cheeseburger",
        "double",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-cheeseburger-meal",
      "chain_id": "mcdonalds",
      "name": "Cheeseburger Meal",
      "category": "combo",
      "price": 156,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cheeseburger",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-big-mac-meal",
      "chain_id": "mcdonalds",
      "name": "Big Mac Meal",
      "category": "combo",
      "price": 284,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "big mac",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-quarter-pounder-with-cheese-meal",
      "chain_id": "mcdonalds",
      "name": "Quarter Pounder with Cheese Meal",
      "category": "combo",
      "price": 284,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "quarter pounder",
        "cheese",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-quarter-pounder-with-cheese-lettuce-tomatoes-meal",
      "chain_id": "mcdonalds",
      "name": "Quarter Pounder with Cheese, Lettuce, & Tomatoes Meal",
      "category": "combo",
      "price": 319,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "quarter pounder",
        "cheese",
        "lettuce",
        "tomato",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-double-quarter-pounder-with-cheese-meal",
      "chain_id": "mcdonalds",
      "name": "Double Quarter Pounder with Cheese Meal",
      "category": "combo",
      "price": 346,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "quarter pounder",
        "double",
        "cheese",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mcchicken-meal",
      "chain_id": "mcdonalds",
      "name": "McChicken Meal",
      "category": "combo",
      "price": 234,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "mcchicken",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-double-mcchicken-meal",
      "chain_id": "mcdonalds",
      "name": "Double McChicken Meal",
      "category": "combo",
      "price": 264,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "mcchicken",
        "double",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-crispy-chicken-fillet-sandwich-with-fries-meal",
      "chain_id": "mcdonalds",
      "name": "Crispy Chicken Fillet Sandwich with Fries Meal",
      "category": "combo",
      "price": 177,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "crispy chicken",
        "fries",
        "sandwich",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-crispy-chicken-sandwich-with-lettuce-tomatoes-meal",
      "chain_id": "mcdonalds",
      "name": "Crispy Chicken Sandwich with Lettuce & Tomatoes Meal",
      "category": "combo",
      "price": 212,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "crispy chicken",
        "lettuce",
        "tomato",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-cheesy-burger-mcdo-meal",
      "chain_id": "mcdonalds",
      "name": "Cheesy Burger McDo Meal",
      "category": "combo",
      "price": 167,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cheesy burger",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-burger-mcdo-meal",
      "chain_id": "mcdonalds",
      "name": "Burger McDo Meal",
      "category": "combo",
      "price": 157,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "burger",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-cheeseburger-with-lettuce-tomatoes",
      "chain_id": "mcdonalds",
      "name": "Cheeseburger with Lettuce & Tomatoes",
      "category": "main",
      "price": 191,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cheeseburger",
        "lettuce",
        "tomato"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-double-cheeseburger-with-lettuce-tomatoes-meal",
      "chain_id": "mcdonalds",
      "name": "Double Cheeseburger with Lettuce & Tomatoes Meal",
      "category": "combo",
      "price": 285,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "double cheeseburger",
        "lettuce",
        "tomato",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-burger-mcdo-with-lettuce-tomatoes-meal",
      "chain_id": "mcdonalds",
      "name": "Burger McDo with Lettuce & Tomatoes Meal",
      "category": "combo",
      "price": 192,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "burger",
        "lettuce",
        "tomato",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-double-big-mac-meal",
      "chain_id": "mcdonalds",
      "name": "Double Big Mac Meal",
      "category": "combo",
      "price": 346,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "big mac",
        "double",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-the-bcb-meal",
      "chain_id": "mcdonalds",
      "name": "The BCB Meal",
      "category": "combo",
      "price": 277,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "bcb",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-cheesburger-with-regular-fries",
      "chain_id": "mcdonalds",
      "name": "Cheesburger with regular fries",
      "category": "main",
      "price": 121,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cheeseburger",
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-golden-chicken-curry-fillet-with-fries-medium-meal",
      "chain_id": "mcdonalds",
      "name": "Golden Chicken Curry Fillet with Fries Medium Meal",
      "category": "combo",
      "price": 181,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "golden chicken",
        "curry",
        "fries",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-golden-chicken-curry-fillet-with-medium-drink",
      "chain_id": "mcdonalds",
      "name": "Golden Chicken Curry Fillet with Medium Drink",
      "category": "combo",
      "price": 1119,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "golden chicken",
        "curry",
        "drink"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-sulit-busog-crispy-chicken-fillet-with-extra-rice-and-regular-drink",
      "chain_id": "mcdonalds",
      "name": "Sulit-Busog Crispy Chicken Fillet with Extra Rice and Regular Drink",
      "category": "combo",
      "price": 103,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "crispy chicken",
        "rice",
        "drink"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-sulit-busog-1-pc-chicken-mcdo-with-extra-rice-and-drink-meal",
      "chain_id": "mcdonalds",
      "name": "Sulit-Busog – 1-pc. Chicken McDo with Extra Rice and Drink Meal",
      "category": "combo",
      "price": 128,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken mcd",
        "rice",
        "drink"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-sulit-busog-crispy-chicken-fillet-ala-king-w-extra-rice",
      "chain_id": "mcdonalds",
      "name": "Sulit-Busog Crispy Chicken Fillet Ala King w Extra Rice",
      "category": "combo",
      "price": 103,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "crispy chicken",
        "ala king",
        "rice"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mega-meal-spicy-chicken-mcdo-w-fries-burger-mcdo",
      "chain_id": "mcdonalds",
      "name": "Mega Meal – Spicy Chicken McDo w Fries & Burger McDo",
      "category": "combo",
      "price": 232,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spicy chicken",
        "fries",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mega-meal-spicy-chicken-mcdo-w-rice-mcspaghetti",
      "chain_id": "mcdonalds",
      "name": "Mega Meal – Spicy Chicken McDo w Rice & McSpaghetti",
      "category": "combo",
      "price": 221,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spicy chicken",
        "rice",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mega-meal-spicy-chicken-mcdo-w-fries-mcflurry",
      "chain_id": "mcdonalds",
      "name": "Mega Meal – Spicy Chicken McDo w Fries & McFlurry",
      "category": "combo",
      "price": 234,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spicy chicken",
        "fries",
        "flurry"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-spicy-chicken-mcdo-w-mcspaghetti-fries-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Spicy Chicken McDo w McSpaghetti Fries Meal",
      "category": "combo",
      "price": 267,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 2,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spicy chicken",
        "spaghetti",
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mega-meal-chicken-mcdo-w-fries-burger-mcdo",
      "chain_id": "mcdonalds",
      "name": "Mega Meal – Chicken McDo w Fries & Burger McDo",
      "category": "combo",
      "price": 226,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "fries",
        "burger"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mega-meal-chicken-mcdo-w-rice-mcspaghetti",
      "chain_id": "mcdonalds",
      "name": "Mega Meal – Chicken McDo w Rice & McSpaghetti",
      "category": "combo",
      "price": 215,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "rice",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mega-meal-chicken-mcdo-w-fries-mcflurry",
      "chain_id": "mcdonalds",
      "name": "Mega Meal – Chicken McDo w Fries & McFlurry",
      "category": "combo",
      "price": 228,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "fries",
        "flurry"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-crispy-chicken-fillet-ala-king-w-fries-meal",
      "chain_id": "mcdonalds",
      "name": "Crispy Chicken Fillet Ala King w Fries Meal",
      "category": "combo",
      "price": 170,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "crispy chicken",
        "ala king",
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-spicy-chicken-mcdo-w-mcspaghetti-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Spicy Chicken McDo w McSpaghetti Meal",
      "category": "combo",
      "price": 206,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spicy chicken",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-chicken-mcdo-w-rice-coke-mcfloat-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Chicken McDo w Rice Coke McFloat Meal",
      "category": "combo",
      "price": 140,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "rice",
        "coke",
        "mcfloat"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-chicken-mcdo-w-mcspaghetti-fries-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Chicken McDo w McSpaghetti Fries Meal",
      "category": "combo",
      "price": 262,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 2,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spaghetti",
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-6-pc-chicken-mcnuggets-w-fries-meal",
      "chain_id": "mcdonalds",
      "name": "6-pc. Chicken McNuggets w Fries Meal",
      "category": "combo",
      "price": 215,
      "serves": 6,
      "main_servings": 0,
      "carb_servings": 1,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "nuggets",
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-6-pc-chicken-mcnuggets-w-rice-meal",
      "chain_id": "mcdonalds",
      "name": "6-pc. Chicken McNuggets w Rice Meal",
      "category": "combo",
      "price": 188,
      "serves": 6,
      "main_servings": 0,
      "carb_servings": 1,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "nuggets",
        "rice"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-chicken-mcdo-w-mcspaghetti-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Chicken McDo w McSpaghetti Meal",
      "category": "combo",
      "price": 201,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spaghetti"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-2-pc-spicy-chicken-mcdo-fries-meal",
      "chain_id": "mcdonalds",
      "name": "2-pc. Spicy Chicken McDo & Fries Meal",
      "category": "combo",
      "price": 298,
      "serves": 2,
      "main_servings": 2,
      "carb_servings": 2,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "spicy chicken",
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-spicy-chicken-mcdo-fries-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Spicy Chicken McDo & Fries Meal",
      "category": "combo",
      "price": 203,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spicy chicken",
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-crispy-chicken-fillet-w-fries-meal",
      "chain_id": "mcdonalds",
      "name": "Crispy Chicken Fillet w Fries Meal",
      "category": "combo",
      "price": 165,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "crispy chicken",
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-sulit-busog-1-pc-chicken-mcdo-meal",
      "chain_id": "mcdonalds",
      "name": "Sulit Busog – 1-pc. Chicken Mcdo Meal",
      "category": "combo",
      "price": 103,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-2-pc-chicken-mcdo-fries-meal",
      "chain_id": "mcdonalds",
      "name": "2-pc. Chicken McDo & Fries Meal",
      "category": "combo",
      "price": 288,
      "serves": 2,
      "main_servings": 2,
      "carb_servings": 2,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-chicken-mcdo-fries-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Chicken McDo & Fries Meal",
      "category": "combo",
      "price": 198,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-2-pc-spicy-chicken-mcdo-meal",
      "chain_id": "mcdonalds",
      "name": "2-pc. Spicy Chicken McDo Meal",
      "category": "combo",
      "price": 241,
      "serves": 2,
      "main_servings": 2,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "spicy chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-spicy-chicken-mcdo-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Spicy Chicken McDo Meal",
      "category": "main",
      "price": 120,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spicy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-8-pc-chicken-mcshare-box",
      "chain_id": "mcdonalds",
      "name": "8-pc. Chicken McShare Box",
      "category": "main",
      "price": 670,
      "serves": 8,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-6-pc-chicken-mcshare-box",
      "chain_id": "mcdonalds",
      "name": "6-pc. Chicken McShare Box",
      "category": "main",
      "price": 513,
      "serves": 6,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-10-pc-chicken-mcnuggets",
      "chain_id": "mcdonalds",
      "name": "10-pc. Chicken McNuggets",
      "category": "main",
      "price": 189,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "nuggets"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-6-pc-chicken-mcnuggets",
      "chain_id": "mcdonalds",
      "name": "6-pc. Chicken McNuggets",
      "category": "main",
      "price": 110,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "nuggets"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-2-pc-chicken-mcdo-meal",
      "chain_id": "mcdonalds",
      "name": "2-pc. Chicken McDo Meal",
      "category": "main",
      "price": 231,
      "serves": 2,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-chicken-mcdo-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Chicken McDo Meal",
      "category": "main",
      "price": 115,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-cotton-candy-mcfloat-medium-fries-combo",
      "chain_id": "mcdonalds",
      "name": "Cotton Candy McFloat & Medium Fries Combo",
      "category": "combo",
      "price": 103,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cotton candy",
        "float",
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-rasberry-mcfloat-medium-fries-combo",
      "chain_id": "mcdonalds",
      "name": "Rasberry McFloat & Medium Fries Combo",
      "category": "combo",
      "price": 103,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "raspberry",
        "float",
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-grape-mcfloat-medium-fries-combo",
      "chain_id": "mcdonalds",
      "name": "Grape McFloat & Medium Fries Combo",
      "category": "combo",
      "price": 103,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "grape",
        "float",
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-matcha-mcflurry-with-oreo-solo-2",
      "chain_id": "mcdonalds",
      "name": "Matcha McFlurry with Oreo Solo",
      "category": "dessert",
      "price": 83,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "matcha",
        "mcflurry",
        "oreo"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-cotton-candy-mcfloat",
      "chain_id": "mcdonalds",
      "name": "Cotton Candy McFloat",
      "category": "drink",
      "price": 61,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cotton candy",
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mcflurry-with-oreo",
      "chain_id": "mcdonalds",
      "name": "McFlurry with Oreo",
      "category": "dessert",
      "price": 70,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "mcflurry",
        "oreo"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-hot-caramel-sundae",
      "chain_id": "mcdonalds",
      "name": "Hot Caramel Sundae",
      "category": "dessert",
      "price": 59,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "sundae",
        "caramel"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-raspberry-mcfloat",
      "chain_id": "mcdonalds",
      "name": "Raspberry McFloat",
      "category": "drink",
      "price": 61,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "raspberry",
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-hot-fudge-sundae",
      "chain_id": "mcdonalds",
      "name": "Hot Fudge Sundae",
      "category": "dessert",
      "price": 59,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "sundae",
        "fudge"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-royal-mcfloat",
      "chain_id": "mcdonalds",
      "name": "Royal McFloat",
      "category": "drink",
      "price": 60,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "royal",
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-grape-mcfloat",
      "chain_id": "mcdonalds",
      "name": "Grape McFloat",
      "category": "drink",
      "price": 61,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "grape",
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-orange-juice",
      "chain_id": "mcdonalds",
      "name": "Orange Juice",
      "category": "drink",
      "price": 85,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "juice",
        "orange"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-coke-mcfloat",
      "chain_id": "mcdonalds",
      "name": "Coke McFloat",
      "category": "drink",
      "price": 82,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coke",
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-apple-juice",
      "chain_id": "mcdonalds",
      "name": "Apple Juice",
      "category": "drink",
      "price": 85,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "juice",
        "apple"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-coke-zero-sugar",
      "chain_id": "mcdonalds",
      "name": "Coke Zero Sugar",
      "category": "drink",
      "price": 77,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coke",
        "zero sugar"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-apple-pie",
      "chain_id": "mcdonalds",
      "name": "Apple Pie",
      "category": "dessert",
      "price": 45,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pie",
        "apple"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-iced-tea",
      "chain_id": "mcdonalds",
      "name": "Iced Tea",
      "category": "drink",
      "price": 85,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "tea",
        "iced"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-sprite",
      "chain_id": "mcdonalds",
      "name": "Sprite",
      "category": "drink",
      "price": 77,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "sprite"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-royal",
      "chain_id": "mcdonalds",
      "name": "Royal",
      "category": "drink",
      "price": 77,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "royal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-golden-mcfloat-medium",
      "chain_id": "mcdonalds",
      "name": "Golden McFloat Medium",
      "category": "drink",
      "price": 63,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "golden",
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-large-shake-shake-fries-cheese-n-mcfloat-combo",
      "chain_id": "mcdonalds",
      "name": "Large Shake Shake Fries Cheese N McFloat Combo",
      "category": "combo",
      "price": 148,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "large",
        "fries",
        "cheese",
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-large-shake-shake-fries-bbq-n-mcfloat-combo",
      "chain_id": "mcdonalds",
      "name": "Large Shake Shake Fries BBQ N McFloat Combo",
      "category": "combo",
      "price": 148,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "large",
        "fries",
        "bbq",
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-extra-crispy-chicken-fillet-ala-king-sauce",
      "chain_id": "mcdonalds",
      "name": "Extra Crispy Chicken Fillet Ala King Sauce",
      "category": "side",
      "price": 11,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "fillet",
        "sauce"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-bff-shake-shake-fries-bbq-n-mcfloat-combo",
      "chain_id": "mcdonalds",
      "name": "BFF Shake Shake Fries BBQ N McFloat Combo",
      "category": "combo",
      "price": 284,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "bff",
        "fries",
        "bbq",
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-shake-shake-fries-cheese-n-mcfloat-combo",
      "chain_id": "mcdonalds",
      "name": "Shake Shake Fries Cheese N McFloat Combo",
      "category": "combo",
      "price": 126,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "fries",
        "cheese",
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-shake-shake-fries-bbq-n-mcfloat-combo",
      "chain_id": "mcdonalds",
      "name": "Shake Shake Fries BBQ N McFloat Combo",
      "category": "combo",
      "price": 126,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "fries",
        "bbq",
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-twister-fries-n-royal-mcfloat-combo",
      "chain_id": "mcdonalds",
      "name": "Twister Fries N Royal McFloat Combo",
      "category": "combo",
      "price": 135,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "twister fries",
        "royal",
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-extra-mushroom-pepper-steak-sauce",
      "chain_id": "mcdonalds",
      "name": "Extra Mushroom Pepper Steak Sauce",
      "category": "side",
      "price": 11,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "mushroom",
        "pepper steak",
        "sauce"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-large-fries-n-mcfloat-combo",
      "chain_id": "mcdonalds",
      "name": "Large Fries N McFloat Combo",
      "category": "combo",
      "price": 138,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "large fries",
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-shake-shake-fries-cheese",
      "chain_id": "mcdonalds",
      "name": "Shake Shake Fries Cheese",
      "category": "side",
      "price": 101,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "fries",
        "cheese"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-extra-sweet-n-sour-sauce",
      "chain_id": "mcdonalds",
      "name": "Extra Sweet N Sour Sauce",
      "category": "side",
      "price": 17,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "sweet and sour",
        "sauce"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-extra-mcspaghetti-sauce",
      "chain_id": "mcdonalds",
      "name": "Extra McSpaghetti Sauce",
      "category": "side",
      "price": 25,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spaghetti",
        "sauce"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-twister-fries-sharing",
      "chain_id": "mcdonalds",
      "name": "Twister Fries Sharing",
      "category": "side",
      "price": 199,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 1,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "twister fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-twister-fries-regular",
      "chain_id": "mcdonalds",
      "name": "Twister Fries Regular",
      "category": "side",
      "price": 99,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "twister fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-thousand-island-sauce",
      "chain_id": "mcdonalds",
      "name": "Thousand Island Sauce",
      "category": "side",
      "price": 18,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "thousand island",
        "sauce"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-shake-shake-fries-bbq",
      "chain_id": "mcdonalds",
      "name": "Shake Shake Fries BBQ",
      "category": "side",
      "price": 101,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "fries",
        "bbq"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-extra-plain-rice",
      "chain_id": "mcdonalds",
      "name": "Extra Plain Rice",
      "category": "rice",
      "price": 40,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "rice"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-extra-mayonnaise",
      "chain_id": "mcdonalds",
      "name": "Extra Mayonnaise",
      "category": "side",
      "price": 17,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "mayonnaise"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-extra-bbq-sauce",
      "chain_id": "mcdonalds",
      "name": "Extra BBQ Sauce",
      "category": "side",
      "price": 17,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "bbq sauce"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-tartar-sauce",
      "chain_id": "mcdonalds",
      "name": "Tartar Sauce",
      "category": "side",
      "price": 17,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "tartar sauce"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-extra-cheese",
      "chain_id": "mcdonalds",
      "name": "Extra Cheese",
      "category": "side",
      "price": 17,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cheese"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-extra-gravy",
      "chain_id": "mcdonalds",
      "name": "Extra Gravy",
      "category": "side",
      "price": 11,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "gravy"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-bff-fries",
      "chain_id": "mcdonalds",
      "name": "BFF Fries",
      "category": "side",
      "price": 175,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-fries",
      "chain_id": "mcdonalds",
      "name": "Fries",
      "category": "side",
      "price": 92,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "fries"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-cheese-dunk",
      "chain_id": "mcdonalds",
      "name": "Cheese Dunk",
      "category": "dessert",
      "price": 55,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cheese",
        "dunk"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-chili-con-carne-dunk",
      "chain_id": "mcdonalds",
      "name": "Chili Con Carne Dunk",
      "category": "dessert",
      "price": 55,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chili con carne",
        "dunk"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-bff-shake-shake-fries-cheese-n-mcfloat-combo",
      "chain_id": "mcdonalds",
      "name": "BFF Shake Shake Fries Cheese N McFloat Combo",
      "category": "combo",
      "price": 284,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "shake",
        "fries",
        "cheese",
        "mcfloat"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-bff-shake-shake-fries-bbq-n-mcfloat-combo-2",
      "chain_id": "mcdonalds",
      "name": "BFF Shake Shake Fries BBQ N McFloat Combo",
      "category": "combo",
      "price": 284,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "shake",
        "fries",
        "bbq",
        "mcfloat"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-bff-fries-n-mcfloat-combo",
      "chain_id": "mcdonalds",
      "name": "BFF Fries N McFloat Combo",
      "category": "combo",
      "price": 285,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "fries",
        "mcfloat"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-8-pc-chicken-mcshare-box-2",
      "chain_id": "mcdonalds",
      "name": "8-pc. Chicken McShare Box",
      "category": "main",
      "price": 670,
      "serves": 8,
      "main_servings": 8,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-6-pc-chicken-mcshare-box-2",
      "chain_id": "mcdonalds",
      "name": "6-pc. Chicken McShare Box",
      "category": "main",
      "price": 513,
      "serves": 6,
      "main_servings": 6,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-20-pc-chicken-mcnuggets",
      "chain_id": "mcdonalds",
      "name": "20-pc. Chicken McNuggets",
      "category": "main",
      "price": 375,
      "serves": 20,
      "main_servings": 20,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "nuggets"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-10-pc-chicken-mcnuggets-2",
      "chain_id": "mcdonalds",
      "name": "10-pc. Chicken McNuggets",
      "category": "main",
      "price": 189,
      "serves": 10,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "chicken",
        "nuggets"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-snack-burger-mcshare",
      "chain_id": "mcdonalds",
      "name": "Snack Burger McShare",
      "category": "main",
      "price": 380,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "burger",
        "beef"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mcshare-bundle-for-4",
      "chain_id": "mcdonalds",
      "name": "McShare Bundle for 4",
      "category": "combo",
      "price": 847,
      "serves": 4,
      "main_servings": 4,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "bundle"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mcshare-bundle-for-3",
      "chain_id": "mcdonalds",
      "name": "McShare Bundle for 3",
      "category": "combo",
      "price": 612,
      "serves": 3,
      "main_servings": 3,
      "carb_servings": 0,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "bundle"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mcspaghetti-platter",
      "chain_id": "mcdonalds",
      "name": "McSpaghetti Platter",
      "category": "main",
      "price": 262,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spaghetti",
        "pasta"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-burger-mcdo-happy-meal",
      "chain_id": "mcdonalds",
      "name": "Burger McDo Happy Meal",
      "category": "main",
      "price": 148,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "burger",
        "beef",
        "happy meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mcspaghetti-happy-meal",
      "chain_id": "mcdonalds",
      "name": "McSpaghetti Happy Meal",
      "category": "main",
      "price": 168,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spaghetti",
        "pasta",
        "happy meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-chicken-mcdo-happy-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Chicken McDo Happy Meal",
      "category": "main",
      "price": 200,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "happy meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-4-pc-chicken-mcnuggets-happy-meal",
      "chain_id": "mcdonalds",
      "name": "4-pc. Chicken McNuggets Happy Meal",
      "category": "main",
      "price": 184,
      "serves": 4,
      "main_servings": 4,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "nuggets",
        "happy meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-cereal-milk-iced-latte",
      "chain_id": "mcdonalds",
      "name": "McCafé Cereal Milk Iced Latte",
      "category": "drink",
      "price": 160,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "iced",
        "latte"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-cereal-milk-iced-coffee",
      "chain_id": "mcdonalds",
      "name": "McCafé Cereal Milk Iced Coffee",
      "category": "drink",
      "price": 83,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "iced",
        "coffee"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-cereal-milk-premium-roast-coffee",
      "chain_id": "mcdonalds",
      "name": "McCafé Cereal Milk Premium Roast Coffee",
      "category": "drink",
      "price": 73,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-premium-roast-coffee",
      "chain_id": "mcdonalds",
      "name": "McCafé Premium Roast Coffee",
      "category": "drink",
      "price": 63,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-iced-coffee-black-medium",
      "chain_id": "mcdonalds",
      "name": "McCafé Iced Coffee Black Medium",
      "category": "drink",
      "price": 59,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "iced",
        "coffee"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-iced-coffee-original",
      "chain_id": "mcdonalds",
      "name": "McCafé Iced Coffee Original",
      "category": "drink",
      "price": 63,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "iced",
        "coffee"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-coffee-float",
      "chain_id": "mcdonalds",
      "name": "McCafé Coffee Float",
      "category": "drink",
      "price": 82,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "float"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-iced-coffee-vanilla",
      "chain_id": "mcdonalds",
      "name": "McCafé Iced Coffee Vanilla",
      "category": "drink",
      "price": 99,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "iced",
        "vanilla"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-iced-coffee-chocolate",
      "chain_id": "mcdonalds",
      "name": "McCafé Iced Coffee Chocolate",
      "category": "drink",
      "price": 79,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "iced",
        "chocolate"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-strawberry-oreo-frappe",
      "chain_id": "mcdonalds",
      "name": "McCafé Strawberry Oreo Frappe",
      "category": "drink",
      "price": 169,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "frappe",
        "strawberry",
        "oreo"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-cappuccino",
      "chain_id": "mcdonalds",
      "name": "Cappuccino",
      "category": "drink",
      "price": 145,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cappuccino"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-espresso",
      "chain_id": "mcdonalds",
      "name": "Espresso",
      "category": "drink",
      "price": 95,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "espresso"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-strawberry-smoothie",
      "chain_id": "mcdonalds",
      "name": "McCafé Strawberry Smoothie",
      "category": "drink",
      "price": 159,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "smoothie",
        "strawberry"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-macchiato",
      "chain_id": "mcdonalds",
      "name": "Macchiato",
      "category": "drink",
      "price": 95,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "macchiato"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-americano",
      "chain_id": "mcdonalds",
      "name": "Americano",
      "category": "drink",
      "price": 135,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "americano"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mochaccino",
      "chain_id": "mcdonalds",
      "name": "Mochaccino",
      "category": "drink",
      "price": 150,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "mochaccino"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-caf-latte",
      "chain_id": "mcdonalds",
      "name": "Café Latte",
      "category": "drink",
      "price": 145,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "latte"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-flat-white",
      "chain_id": "mcdonalds",
      "name": "Flat White",
      "category": "drink",
      "price": 145,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "flat white"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-iced-chocolate",
      "chain_id": "mcdonalds",
      "name": "McCafé Iced Chocolate",
      "category": "drink",
      "price": 149,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "iced",
        "chocolate"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-iced-americano",
      "chain_id": "mcdonalds",
      "name": "McCafé Iced Americano",
      "category": "drink",
      "price": 140,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "iced",
        "americano"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-iced-latte",
      "chain_id": "mcdonalds",
      "name": "McCafé Iced Latte",
      "category": "drink",
      "price": 150,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "iced",
        "latte"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-iced-c",
      "chain_id": "mcdonalds",
      "name": "McCafé Iced c",
      "category": "drink",
      "price": 155,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "iced"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-caramel-frappe",
      "chain_id": "mcdonalds",
      "name": "McCafé Caramel Frappe",
      "category": "drink",
      "price": 169,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "frappe",
        "caramel"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-caramel-oreo-frappe",
      "chain_id": "mcdonalds",
      "name": "McCafé Caramel Oreo Frappe",
      "category": "drink",
      "price": 179,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "frappe",
        "caramel",
        "oreo"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-mocha-frappe",
      "chain_id": "mcdonalds",
      "name": "McCafé Mocha Frappe",
      "category": "drink",
      "price": 169,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "frappe",
        "mocha"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-mocha-oreo-frappe",
      "chain_id": "mcdonalds",
      "name": "McCafé Mocha Oreo Frappe",
      "category": "drink",
      "price": 179,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "frappe",
        "mocha",
        "oreo"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-double-choco-frappe",
      "chain_id": "mcdonalds",
      "name": "McCafé Double Choco Frappe",
      "category": "drink",
      "price": 169,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "frappe",
        "chocolate"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-jasmine-tea",
      "chain_id": "mcdonalds",
      "name": "McCafé Jasmine Tea",
      "category": "drink",
      "price": 99,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "tea"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-peppermint-tea",
      "chain_id": "mcdonalds",
      "name": "McCafé Peppermint Tea",
      "category": "drink",
      "price": 99,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "tea"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-black-tea",
      "chain_id": "mcdonalds",
      "name": "McCafé Black Tea",
      "category": "drink",
      "price": 99,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "tea"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-iced-tea",
      "chain_id": "mcdonalds",
      "name": "McCafé Iced Tea",
      "category": "drink",
      "price": 129,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "tea",
        "iced"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-dalandan-smoothie",
      "chain_id": "mcdonalds",
      "name": "McCafé Dalandan Smoothie",
      "category": "drink",
      "price": 159,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "smoothie",
        "fruit"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-choco-chip-cookies",
      "chain_id": "mcdonalds",
      "name": "Choco Chip Cookies",
      "category": "side",
      "price": 84,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cookie",
        "chocolate"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-choco-chip-banana-slice",
      "chain_id": "mcdonalds",
      "name": "Choco Chip Banana Slice",
      "category": "side",
      "price": 89,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "banana",
        "cookie"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-caramel-cinnamon",
      "chain_id": "mcdonalds",
      "name": "Caramel Cinnamon",
      "category": "side",
      "price": 114,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "pastry",
        "cinnamon"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-cheese-and-bacon-croissant",
      "chain_id": "mcdonalds",
      "name": "Cheese and Bacon Croissant",
      "category": "side",
      "price": 139,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "croissant",
        "cheese",
        "bacon"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-sausage-croissant",
      "chain_id": "mcdonalds",
      "name": "Sausage Croissant",
      "category": "side",
      "price": 139,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "croissant",
        "sausage"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-dark-chocolate-cake",
      "chain_id": "mcdonalds",
      "name": "Dark Chocolate Cake",
      "category": "dessert",
      "price": 160,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cake",
        "chocolate"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-blueberry-cheesecake",
      "chain_id": "mcdonalds",
      "name": "Blueberry Cheesecake",
      "category": "dessert",
      "price": 180,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cheesecake",
        "blueberry"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-oreo-cheesecake",
      "chain_id": "mcdonalds",
      "name": "Oreo Cheesecake",
      "category": "dessert",
      "price": 180,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "cheesecake",
        "oreo"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-chicken-pesto-wrap",
      "chain_id": "mcdonalds",
      "name": "Chicken Pesto Wrap",
      "category": "main",
      "price": 179,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "wrap"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-americano-2",
      "chain_id": "mcdonalds",
      "name": "Americano",
      "category": "drink",
      "price": 120,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-cafe-latte",
      "chain_id": "mcdonalds",
      "name": "Cafe Latte",
      "category": "drink",
      "price": 130,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee",
        "latte"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mochaccino-2",
      "chain_id": "mcdonalds",
      "name": "Mochaccino",
      "category": "drink",
      "price": 135,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee",
        "mocha"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-americano-medium",
      "chain_id": "mcdonalds",
      "name": "McCafé Americano Medium",
      "category": "drink",
      "price": 110,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee",
        "medium"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-iced-mocha",
      "chain_id": "mcdonalds",
      "name": "Iced Mocha",
      "category": "drink",
      "price": 149,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee",
        "iced",
        "mocha"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-iced-latte",
      "chain_id": "mcdonalds",
      "name": "Iced Latte",
      "category": "drink",
      "price": 99,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee",
        "iced",
        "latte"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-iced-americano",
      "chain_id": "mcdonalds",
      "name": "Iced Americano",
      "category": "drink",
      "price": 124,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee",
        "iced",
        "americano"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-cappuccino-medium",
      "chain_id": "mcdonalds",
      "name": "McCafé Cappuccino Medium",
      "category": "drink",
      "price": 139,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee",
        "cappuccino",
        "medium"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-iced-americano-medium",
      "chain_id": "mcdonalds",
      "name": "McCafé Iced Americano Medium",
      "category": "drink",
      "price": 99,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee",
        "iced",
        "americano",
        "medium"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-iced-latte-medium",
      "chain_id": "mcdonalds",
      "name": "McCafé Iced Latte Medium",
      "category": "drink",
      "price": 99,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee",
        "iced",
        "latte",
        "medium"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-iced-mocha-medium",
      "chain_id": "mcdonalds",
      "name": "McCafé Iced Mocha Medium",
      "category": "drink",
      "price": 99,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee",
        "iced",
        "mocha",
        "medium"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-mochaccino-medium",
      "chain_id": "mcdonalds",
      "name": "McCafé Mochaccino Medium",
      "category": "drink",
      "price": 99,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee",
        "mochaccino",
        "medium"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mccaf-hot-latte-medium",
      "chain_id": "mcdonalds",
      "name": "McCafé Hot Latte Medium",
      "category": "drink",
      "price": 99,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "coffee",
        "latte",
        "medium"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-chicken-mcdo-with-mcspaghetti-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Chicken McDo with McSpaghetti Meal",
      "category": "combo",
      "price": 201,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spaghetti",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-spicy-chicken-mcdo-with-mcspaghetti-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Spicy Chicken McDo with McSpaghetti Meal",
      "category": "combo",
      "price": 206,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spicy chicken",
        "spaghetti",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-chicken-mcdo-with-mcspaghetti-fries-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Chicken McDo with McSpaghetti & Fries Meal",
      "category": "combo",
      "price": 262,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 2,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "spaghetti",
        "fries",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-spicy-chicken-mcdo-with-mcspaghetti-fries-meal",
      "chain_id": "mcdonalds",
      "name": "1-pc. Spicy Chicken McDo with McSpaghetti & Fries Meal",
      "category": "combo",
      "price": 267,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 2,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spicy chicken",
        "spaghetti",
        "fries",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mega-meal-chicken-mcdo-with-rice-mcspaghetti",
      "chain_id": "mcdonalds",
      "name": "Mega Meal – Chicken McDo with Rice & McSpaghetti",
      "category": "combo",
      "price": 215,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 2,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "rice",
        "spaghetti",
        "mega"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mega-meal-spicy-chicken-mcdo-with-rice-mcspaghetti",
      "chain_id": "mcdonalds",
      "name": "Mega Meal – Spicy Chicken McDo with Rice & McSpaghetti",
      "category": "combo",
      "price": 221,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 2,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spicy chicken",
        "rice",
        "spaghetti",
        "mega"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mcspaghetti-with-fries-meal",
      "chain_id": "mcdonalds",
      "name": "McSpaghetti with Fries Meal",
      "category": "combo",
      "price": 168,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 2,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spaghetti",
        "fries",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mcspaghetti-meal",
      "chain_id": "mcdonalds",
      "name": "McSpaghetti Meal",
      "category": "combo",
      "price": 105,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spaghetti",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-mcspaghetti-with-burger-mcdo-meal",
      "chain_id": "mcdonalds",
      "name": "McSpaghetti with Burger McDo Meal",
      "category": "combo",
      "price": 149,
      "serves": 1,
      "main_servings": 2,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "spaghetti",
        "burger",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-sulit-busog-1-pc-mushroom-pepper-steak-with-extra-rice-meal",
      "chain_id": "mcdonalds",
      "name": "Sulit-Busog 1 pc. Mushroom Pepper Steak with Extra Rice Meal",
      "category": "combo",
      "price": 103,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 2,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "steak",
        "rice",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-2-pc-mushroom-pepper-steak-fries-meal",
      "chain_id": "mcdonalds",
      "name": "2 pc. Mushroom Pepper Steak & Fries Meal",
      "category": "combo",
      "price": 208,
      "serves": 2,
      "main_servings": 2,
      "carb_servings": 2,
      "shareable": true,
      "is_combo": false,
      "tags": [
        "steak",
        "fries",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-1-pc-mushroom-pepper-steak-fries-meal",
      "chain_id": "mcdonalds",
      "name": "1 pc. Mushroom Pepper Steak & Fries Meal",
      "category": "combo",
      "price": 143,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 2,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "steak",
        "fries",
        "meal"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-sulit-busog-golden-chicken-curry-fillet-with-extra-rice-meal",
      "chain_id": "mcdonalds",
      "name": "Sulit Busog Golden Chicken Curry Fillet with Extra Rice Meal",
      "category": "combo",
      "price": 103,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-sulit-busog-crispy-chicken-fillet-with-extra-rice-and-regular-drink-2",
      "chain_id": "mcdonalds",
      "name": "Sulit-Busog Crispy Chicken Fillet with Extra Rice and Regular Drink",
      "category": "combo",
      "price": 128,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "drink"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-sulit-busog-1-pc-chicken-mcdo-with-extra-rice-and-drink-meal-2",
      "chain_id": "mcdonalds",
      "name": "Sulit-Busog – 1-pc. Chicken McDo with Extra Rice and Drink Meal",
      "category": "combo",
      "price": 128,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "drink"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-sulit-busog-1-pc-mushroom-pepper-steak-with-extra-rice-meal-2",
      "chain_id": "mcdonalds",
      "name": "Sulit-Busog – 1-pc. Mushroom Pepper Steak with Extra Rice Meal",
      "category": "combo",
      "price": 103,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-sulit-busog-crispy-chicken-fillet-ala-king-w-extra-rice-2",
      "chain_id": "mcdonalds",
      "name": "Sulit-Busog Crispy Chicken Fillet Ala King w Extra Rice",
      "category": "combo",
      "price": 103,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 1,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-sulit-busog-1-pc-chicken-mcdo-meal-2",
      "chain_id": "mcdonalds",
      "name": "Sulit Busog – 1-pc. Chicken Mcdo Meal",
      "category": "combo",
      "price": 103,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-fifa-world-cup-chicken-mcnuggets-meal",
      "chain_id": "mcdonalds",
      "name": "FIFA World Cup Chicken McNuggets Meal",
      "category": "combo",
      "price": 242,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-fifa-collectible-cup-meal-6-pc-chicken-mcnuggets",
      "chain_id": "mcdonalds",
      "name": "FIFA Collectible Cup Meal 6-pc. Chicken McNuggets",
      "category": "combo",
      "price": 284,
      "serves": 1,
      "main_servings": 6,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-fifa-goalden-bundle-2-cheeseburgers",
      "chain_id": "mcdonalds",
      "name": "FIFA GOALden Bundle 2 Cheeseburgers",
      "category": "combo",
      "price": 449,
      "serves": 2,
      "main_servings": 2,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-a-w-root-beer-mcfloat-and-fries-combo",
      "chain_id": "mcdonalds",
      "name": "A&W Root Beer McFloat and Fries Combo",
      "category": "combo",
      "price": 101,
      "serves": 1,
      "main_servings": 0,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "drink",
        "side"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-fifa-goalden-bundle-10-pc-chicken-mcnuggets",
      "chain_id": "mcdonalds",
      "name": "FIFA GOALden Bundle 10-pc. Chicken McNuggets",
      "category": "combo",
      "price": 469,
      "serves": 1,
      "main_servings": 10,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-fifa-collectible-cup-meal-cheeseburger",
      "chain_id": "mcdonalds",
      "name": "FIFA Collectible Cup Meal Cheeseburger",
      "category": "combo",
      "price": 258,
      "serves": 1,
      "main_servings": 1,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "beef"
      ],
      "available": true,
      "price_confidence": "verified"
    },
    {
      "id": "mc-6-pc-chicken-mcnuggets-w-fries-and-a-w-root-beer",
      "chain_id": "mcdonalds",
      "name": "6-pc. Chicken McNuggets w Fries and A&W Root Beer",
      "category": "combo",
      "price": 222,
      "serves": 1,
      "main_servings": 6,
      "carb_servings": 0,
      "shareable": false,
      "is_combo": false,
      "tags": [
        "chicken",
        "side",
        "drink"
      ],
      "available": true,
      "price_confidence": "verified"
    }
  ]
};
